const products = [
  // --- LUBRICANTES ---
{
    id: 1,
    name: 'Caja 12/u de aceite semisintetico 2T',
    category: 'Lubricantes',
    price: 7.25,
    iva: 10.5, // 10.5% 
    badge: '',
    brand: 'Shimaha',
    specs: ['Aceite 2T 1L', 'Caja 12 unidades', 'Semisintético'],
    image: '/fotos/Aceite/2TSS-1L.jpg',
    description: 'Ideal para uso intensivo en maquinas y herramientas de jardin.'
  },
  {
    id: 2,
    name: 'Caja 4/u de aceite semisintetico 2T',
    category: 'Lubricantes',
    price: 20.00,
    iva: 10.5,
    badge: '',
    brand: 'Shimaha',
    specs: ['Aceite 2T 4L', 'Caja 4 unidades', 'Semisintético'],
    image: '/fotos/Aceite/2TSS 4L.jpg',
    description: 'Ideal para uso intensivo en maquinas y herramientas de jardin.'
  },
  {
    id: 3,
    name: 'Aceite Semisintético 2T',
    category: 'Lubricantes',
    price: 604.35,
    iva: 10.5,
    badge: '',
    brand: 'Shimaha',
    specs: ['Aceite 2T 200L', 'Semisintético'],
    image: '/fotos/Aceite/2TSS-200L.jpg',
    description: 'Ideal para uso intensivo en maquinas y herramientas de jardin.'
  },
  {
    id: 4,
    name: 'Caja 24/u de aceite semisintetico 2T',
    category: 'Lubricantes',
    price: 1.45,
    iva: 10.5,
    badge: '',
    brand: 'Shimaha',
    specs: ['Aceite 2T 100cc', 'Caja 24 unidades', 'Semisintético'],
    image: '/fotos/aceite/2TSS-100cc.jpg',
    description: 'Ideal para uso intensivo en maquinas y herramientas de jardin.'
  },
  {
    id: 5,
    name: 'Caja 12/u de aceite semisintetico 4T',
    category: 'Lubricantes',
    price: 5.40,
    iva: 10.5,
    badge: '',
    brand: 'Shimaha',
    specs: ['Aceite 4T 1L', 'Caja 12 unidades', 'Semisintético'],
    image: '/fotos/aceite/4TSAE-1L.jpg',
    description: 'Ideal para uso intensivo en maquinas y herramientas de jardin.'
  },
  {
    id: 6,
    name: 'Aceite Semisintético 4T',
    category: 'Lubricantes',
    price: 558.45,
    iva: 10.5,
    badge: '',
    brand: 'Shimaha',
    specs: ['Aceite 4T 200L', 'Semisintético'],
    image: '/fotos/aceite/4TSAE-200L.jpg',
    description: 'Ideal para uso intensivo en maquinas y herramientas de jardin.'
  },
  {
    id: 7,
    name: 'Caja 12/u de aceite semisintetico',
    category: 'Lubricantes',
    price: 5,
    iva: 10.5,
    badge: '',
    brand: 'Shimaha',
    specs: ['Aceite para cadenas 1L', 'Caja 12 unidades', 'Semisintético'],
    image: '/fotos/aceite/CHAIN 1L.jpg',
    description: 'Ideal para cadenas de motosierras.'
  },


  // --- AIRE Y NEUMATICA ---
  {
    id: 8,
    name: 'Compresor de transmision directa ',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Compresores',
    price: 129,
    iva: 10.5,
    badge: '',
    brand: 'Shimaha',
    specs: ['2hp', '25L', 'Uso hogareño'],
    image: '/fotos/Aire y neumatica/WD-2025.jpg',
    description: 'Compresor de transmisión directa, caudal de 147 L/min y presion de 8 bar.'
  },
  {
    id: 9,
    name: 'Compresor transmisión directa',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Compresores',
    price: 117,
    iva: 10.5,
    badge: '',
    brand: 'Shimaha',
    specs: ['8bar', '2,5 hp', '50L', 'Uso hogareño'],
    image: '/fotos/Aire y neumatica/ZA-2050.jpg',
    description: 'Compresor de transmisión directa, caudal de 206 L/min a 8 bar de presión constante.'
  },
  {
    id: 10,
    name: 'Compresor transmisión directa',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Compresores',
    price: 140,
    iva: 10.5,
    badge: '',
    brand: 'Shimaha',
    specs: ['8bar', '2,5 hp', '50L', 'Uso hogareño'],
    image: '/fotos/Aire y neumatica/ZA-2050-K3.jpg',
    description: 'Compresor de transmisión directa, caudal de 206 L/min y presion de 8 bar. Incluye kit de 3 piezas'
  },
  {
    id: 11,
    name: 'Compresor de transmisión indirecta',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Compresores',
    price: 490,
    iva: 10.5,
    badge: '',
    brand: 'Shimaha',
    specs: ['3 hp', '100L', 'Uso intensivo'],
    image: '/fotos/Aire y neumatica/compresor1.jpg',
    description: 'Compresor de transmisión indirecto a correa, caudal de 310 L/min.'
  },
  {
    id: 12,
    name: 'Compresor de transmisión a correa',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Compresores',
    price: 589,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['3 hp', '150L', 'Uso intensivo'],
    image: '/fotos/Aire y neumatica/compresor2.jpg',
    description: 'Compresor de transmisión a correa, caudal de 310 L/min.'
  },
  {
    id: 13,
    name: 'Compresor de transmisión a correa',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Compresores',
    price: 764,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['5,5 hp', '100L', 'Uso intensivo'],
    image: '/fotos/Aire y neumatica/AMX-55100P.jpg',
    description: 'Compresor de transmisión a correa, caudal de 335 L/min.'
  },
  {
    id: 14,
    name: 'Compresor de transmisión a correa',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Compresores',
    price: 1030,
    iva: 10.5,
    badge: 'PROXIMAMENTE',
    brand: 'AMX',
    specs: ['5,5 hp', '300L', 'Uso intensivo'],
    image: '/fotos/Aire y neumatica/AMX-55300.jpg',
    description: 'Compresor de transmisión a correa, caudal de 580 L/min.'
  },
  {
    id: 15,
    name: 'Compresor de transmisión a correa',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Compresores',
    price: 1541,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['7,5 hp', '500L', 'Uso intensivo'],
    image: '/fotos/Aire y neumatica/AMX-75500.jpg',
    description: 'Compresor de transmisión a correa, caudal de 900 L/min.'
  },
  {
    id: 16,
    name: 'Llave de impacto neumática 1/2"',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 30,
    iva: 21,
    badge: '',
    brand: 'AMX',
    specs: ['1/2"', '400 Nm'],
    image: '/fotos/Aire y neumatica/AT-4070.jpg',
    description: 'Llave de impacto neumática 1/2" con doble martillo y torque maximo de 400 Nm.'
  },
  {
    id: 17,
    name: 'Taladro neumatico reversible',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 24,
    iva: 21,
    badge: '',
    brand: 'AMX',
    specs: ['3/8"'], 
    image: '/fotos/Aire y neumatica/AT-4031.jpg',
    description: 'Taladro neumático reversible de 3/8" (10 mm), compacto y liciano con peso de 1,2 kg.'
  },
  {
    id: 18,
    name: 'Pico de inflado de neumáticos',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 2.50,
    iva: 21,
    badge: '',
    brand: 'AMX',
    specs: [''],
    image: '/fotos/Aire y neumatica/AA-3065.jpg',
    description: 'Pico de inflado de neumáticos.'
  },
  {
    id: 19,
    name: 'Mini regulador',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 2.50,
    iva: 21,
    badge: '',
    brand: 'AMX',
    specs: [''],
    image: '/fotos/Aire y neumatica/AA-2006.jpg',
    description: 'Mini regulador neumatico, con conezion de 1/4", ideal para regular el flujo de aire.'
  },
  {
    id: 20,
    name: 'Union articulada neumatica',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 5,
    iva: 21,
    badge: '',
    brand: 'AMX',
    specs: [''],
    image: '/fotos/Aire y neumatica/AA-2005.jpg',
    description: 'Union articulada neumatica con conexion de 1/4", diseñada para facilitar conexiones flexibles.'
  },
  {
    id: 21,
    name: 'Filtro y regulador de aire',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 17,
    iva: 21,
    badge: '',
    brand: 'AMX',
    specs: [''],
    image: '/fotos/Aire y neumatica/AA-2027.jpg',
    description: 'Filtro y regulador de aire para controlar la presion y filtrar impurezas del sistema neumatico.'
  },
  {
    id: 22,
    name: 'Amoladora angular neumatica',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 50,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['Disco de 5"', '90 psi', '11.000 rpm', '2 Hp'],
    image: '/fotos/Aire y neumatica/AT-7037.jpg',
    description: 'Amoladora angular neumatica con disco de 5", presion de trabajo de 90 psi y consumo de 170 L/min.'
  },
  {
    id: 23,
    name: 'Amoladora recta neumatica',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 19,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['1.5 Hp', '90 psi'],
    image: '/fotos/Aire y neumatica/AT-7033K.jpg',
    description: 'Amoladora recta neumatica con boquilla de 1/4", consumo de 143 L/min y presion de trabajo de 90 psi.'
  },
  {
    id: 24,
    name: 'Amoladora recta neumatica',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 14,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['22.000rpm', '1.5 Hp', '90 psi'],
    image: '/fotos/Aire y neumatica/AT-7033.jpg',
    description: 'Amoladora recta neumatica con boquilla de 1/4", (6,35 mm), consumo de 143 L/min y presion de trabajo de 90 psi.'
  },
  {
    id: 25, 
    name: 'Amoladora recta neumatica',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 24,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['1,5 Hp', '90 psi' ],
    image: '/fotos/Aire y neumatica/AT-7033L.jpg',
    description: 'Amoladora recta neumatica con boquilla de 1/4", (6,35 mm), eje de 15cm, consumo de 143 L/min y presion de trabajo de 90 psi.'
  },
  {
    id: 26,
    name: 'Amoladora para gomeria y metal',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 37,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['1,5 Hp', '90 psi', '22.000 rpm'],
    image: '/fotos/Aire y neumatica/AT-6055.jpg',
    description: 'Amoladora para gomeria y metal con boquilla de 1/4", (6,35 mm), consumo de 140 L/min y presion de trabajo de 90 psi.'
  },
  {
    id: 27,
    name: 'Microamoladora neumatica',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 20,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['1,5 Hp', '90 psi'],
    image: '/fotos/Aire y neumatica/microamoladora.jpg',
    description: 'Microamoladora neumatica con presion de trabajo de 90 psi, incluye kit de piedra y lubricador.'
  },
  {
    id: 28,
    name: 'Martillo neumatico',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 28,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['3.000 impactos por minuto', '90 psi'],
    image: '/fotos/Aire y neumatica/AT-2020.jpg',
    description: 'Martillo neumatico de encastre redondo, 3.000 impactos por minuto, consumo de 157 L/min y presion de trabajo de 90 psi.'
  },
  {
    id: 29,
    name: 'Clavadora neumatica',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 30,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['90 psi', '2 Hp' ],
    image: '/fotos/Aire y neumatica/F-50.jpg',
    description: 'Clavadora neumatica para clavos de 1-25 mm, largo de 16-40 mm, presion de 90 psi y consumo de 1,13 L/disparo.'
  },
  {
    id: 30,
    name: 'Clavadora paletera',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 240,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['90 psi', '2 Hp' ],
    image: '/fotos/Aire y neumatica/CN90.jpg',
    description: 'Clavadora paletera para clavos de  0 2,8-38  mm, largo de 50-90 mm, presion de 90 psi y consumo de 1,13 L/disparo.'
  },
  {
    id: 31,
    name: 'Clavadora de palma',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 29,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['90 psi', '1.5 Hp' ],
    image: '/fotos/Aire y neumatica/AT-3100.jpg',
    description: 'Clavadora de palma para clavos tipo paris con presion de trabajo de 90 psi y consumo de 0,85 L/min.'
  },
  {
    id: 32,
    name:'Clavadora/grampadora neumatica',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 32,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['' ],
    image: '/fotos/Aire y neumatica/F-50 9040.jpg',
    description: 'Clavadora/grampadora neumatica para clavos de 1-25 mm, largo de 16-40 mm, y capacidad de 5,7 mm.'
  },
  {
    id: 33,
    name: 'Minicompresor',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 104,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['1/4 Hp', '200W', ],
    image: '/fotos/Aire y neumatica/AS-06K.jpg',
    description: 'Minicompresor con manguera reforzada, pìstola metalica y embudo de viscocidad.'
  },
  {
    id:34,
    name: 'Engrapadora neumatica',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 29,
    iva: 10.5,
    badge:'',
    brand:'AMX', 
    specs:[''],
    image:'/fotos/Aire y neumatica/8416.jpg',
    description:'Engrapadora neumatica para grampas de 12,8 mm de ancho, largo de 8-16mm y peso de 1,8Kg.'
  },
  {
    id:35,
    name: 'Engrapadora neumatica',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 28,
    iva: 10.5,
    badge:'',
    brand:'AMX', 
    specs:['90 psi'],
    image:'/fotos/Aire y neumatica/engrapadora.jpg',
    description:'Engrapadora neumatica con capacidad de 10,1 mm, largo de 8-14 mm, presion de trabajo de 90 psi y consumo de 0,11 L/disparo.'
  },
  {
    id:36,
    name: 'Engrapadora neumatica',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 26,
    iva: 10.5,
    badge:'',
    brand:'AMX', 
    specs:['2 Hp', '90 psi'],
    image:'/fotos/Aire y neumatica/9040.jpg',
    description:'Engrapadora neumatica con capacidad de 5,7 mm, largo de 16-40 mm, presion de trabajo de 90 psi y consumo de 0,11 L/disparo'
  },
  {
    id:37,
    name: 'Taladro angular',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 40,
    iva: 10.5,
    badge:'',
    brand:'AMX', 
    specs:['1800 rpm'],
    image:'/fotos/Aire y neumatica/AT-4036-6.jpg',
    description:'Taladro angular neumatico de hasta 10 mm, compacto y diseñado para trabajar en espacios reducidos'
  },
  {
    id:38,
    name: 'Taladro neumatico reversible',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 30,
    iva: 10.5,
    badge:'',
    brand: 'AMX', 
    specs:[''],
    image:'/fotos/Aire y neumatica/AT-4041.jpg',
    description:'Taladro neumatico reversible con mandril de 13 mm y mango de fuerza.'
  },
  {
    id:39,
    name: 'Atornillador neumatico',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 58,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['8.000 rpm', '1.5 Hp'],
    image:'/fotos/Aire y neumatica/AT-4060A.jpg',
    description:'Atornillador neumatico'
  },
  {
    id:40,
    name: 'Cortadora neumatica',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 15,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['22.000rpm', '1.5 Hp', '90 psi'],
    image:'/fotos/Aire y neumatica/cortadoraneumatica.jpg',
    description:'Cortadora neumatica de metales para discos de 3", consumo de 170 L/min y presion de trabajo de 90 psi'
  },
  {
    id:41,
    name: 'Equipo de pintar',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 24,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['600W'],
    image:'/fotos/Aire y neumatica/LL01.jpg',
    description:'Equipo de pintar con pistola plastica, accesorios incluidos y diseñado para uso hobbista'
  },
  {
    id:42,
    name: 'Equipo de pintar',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 56,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['600W'],
    image:'/fotos/Aire y neumatica/LL07.jpg',
    description:'Equipo de pintar con pistola metalica, apto para esmalte y laca para uso semiprofesional'
  },
  {
    id:43,
    name: 'Llave de impacto',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 30,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['7.000rpm', '2 Hp'],
    image:'/fotos/Aire y neumatica/AT-5040.jpg',
    description:'LLave de impacto neumatica, con encastre de 1/2", torque de 230 lb/pie y consumo de 0.22 m/min.'
  },
   {
    id:44,
    name: 'Kit de llave de impacto',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 43,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/AT-5004.jpg',
    description:'Kit de llave de impacto con estuche, 10 tubos de alto impacto, extension y minilubricador.'
  },
  {
    id:45,
    name: 'Llave de impacto',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 210,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['3.800rpm', '5 Hp'],
    image:'/fotos/Aire y neumatica/AT-6081.jpg',
    description:'Llave de impacto neumatica con encasre de 1", torque de 1.250 lb/pie y consumo de 1 L/min.'
  },
  {
    id:46,
    name: 'Llave de impacto',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 61,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['7.000rpm', '2 Hp'],
    image:'/fotos/Aire y neumatica/AT-5044.jpg',
    description:'Llave de impacto para uso industrial,con encastre de 1/2", torque de 370 lb/pie y consumo de 0,23 m/min.'
  },
  {
    id:47,
    name: 'Llave de impacto',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 134 ,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['4.500rpm', '3 Hp'],
    image:'/fotos/Aire y neumatica/AT-430-2.jpg',
    description:'Llave de impacto para uso pesado con encastre de 3/4", torque de 500lb/pie y consumo de 0,34 m/min.'
  },
  {
    id:48,
    name: 'Kit llave de impacto',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 29,
    iva: 10.5,
    badge:'', 
    brand:'AMC',
    specs:[''],
    image:'/fotos/Aire y neumatica/AT-4007.jpg',
    description:'Kit de llave de impacto con 10 tubos de alto impacto, extension, minilubricador y estuche-'
  },
  









  // --- CONSTRUCCIÓN ---
  {
    id: 8,
    name: 'Hormigonera Mezcladora Obra 140L',
    category: 'Construcción',
    price: 590000,
    badge: 'Profesional',
    brand: 'Obra',
    specs: ['Tambor 140L', 'Motor 550W', 'Boca 380 mm', 'Aislación Clase II'],
    image: 'https://images.unsplash.com/photo-1541888946425-d0fbb186c5f7?w=800&auto=format&fit=crop&q=80',
    description: 'Tambor de chapa reforzada con protección térmica Clase II. Corona y piñón de fundición diseñados para trabajo pesado en obra.'
  },
  {
    id: 9,
    name: 'Carretilla Obra Reforzada 120L 160kg',
    category: 'Construcción',
    price: 165000,
    badge: '',
    brand: 'Obra',
    specs: ['Capacidad 160 Kg', 'Volumen 120L', 'Chapa 0.9 mm', 'Rueda Neumática'],
    image: 'https://images.unsplash.com/photo-1584467735815-f778f274e296?w=800&auto=format&fit=crop&q=80',
    description: 'Batea embutida de chapa reforzada de 0.9 mm, chasis tubular con trabas delanteras anti-volcadura y rueda de alta tracción.'
  },

  // --- ENERGÍA ---
  {
    id: 10,
    name: 'Generador Naftero Shimaha 6.5 kW con Arranque',
    category: 'Energía',
    price: 1350000,
    badge: 'Esencial',
    brand: 'Shimaha',
    specs: ['Potencia 6.5 kW', 'Motor 16 HP 4T', 'Salida 220V', 'Batería incluida'],
    image: 'https://images.unsplash.com/photo-1513828583688-c52646db42da?w=800&auto=format&fit=crop&q=80',
    description: 'Generador profesional con regulación automática de voltaje (AVR), arranque eléctrico/manual, voltímetro y kit de ruedas de traslado.'
  }
];