const products = [
  // --- LUBRICANTES ---
{
    id: 1,
    name: 'Caja 12/u de aceite semisintetico 2T',
    category: 'Lubricantes',
    price: 7.25,
    iva: 10.5, // 10.5% 
    badge: '',
    brand: 'Shimaha',
    specs: ['Aceite 2T 1L', 'Caja 12 unidades', 'Semisintético'],
    image: '/fotos/Aceite/2TSS-1L.jpg',
    description: 'Ideal para uso intensivo en maquinas y herramientas de jardin.'
  },
  {
    id: 2,
    name: 'Caja 4/u de aceite semisintetico 2T',
    category: 'Lubricantes',
    price: 20.00,
    iva: 10.5,
    badge: '',
    brand: 'Shimaha',
    specs: ['Aceite 2T 4L', 'Caja 4 unidades', 'Semisintético'],
    image: '/fotos/Aceite/2TSS 4L.jpg',
    description: 'Ideal para uso intensivo en maquinas y herramientas de jardin.'
  },
  {
    id: 3,
    name: 'Aceite Semisintético 2T',
    category: 'Lubricantes',
    price: 604.35,
    iva: 10.5,
    badge: '',
    brand: 'Shimaha',
    specs: ['Aceite 2T 200L', 'Semisintético'],
    image: '/fotos/Aceite/2TSS-200L.jpg',
    description: 'Ideal para uso intensivo en maquinas y herramientas de jardin.'
  },
  {
    id: 4,
    name: 'Caja 24/u de aceite semisintetico 2T',
    category: 'Lubricantes',
    price: 1.45,
    iva: 10.5,
    badge: '',
    brand: 'Shimaha',
    specs: ['Aceite 2T 100cc', 'Caja 24 unidades', 'Semisintético'],
    image: '/fotos/aceite/2TSS-100cc.jpg',
    description: 'Ideal para uso intensivo en maquinas y herramientas de jardin.'
  },
  {
    id: 5,
    name: 'Caja 12/u de aceite semisintetico 4T',
    category: 'Lubricantes',
    price: 5.40,
    iva: 10.5,
    badge: '',
    brand: 'Shimaha',
    specs: ['Aceite 4T 1L', 'Caja 12 unidades', 'Semisintético'],
    image: '/fotos/aceite/4TSAE-1L.jpg',
    description: 'Ideal para uso intensivo en maquinas y herramientas de jardin.'
  },
  {
    id: 6,
    name: 'Aceite Semisintético 4T',
    category: 'Lubricantes',
    price: 558.45,
    iva: 10.5,
    badge: '',
    brand: 'Shimaha',
    specs: ['Aceite 4T 200L', 'Semisintético'],
    image: '/fotos/aceite/4TSAE-200L.jpg',
    description: 'Ideal para uso intensivo en maquinas y herramientas de jardin.'
  },
  {
    id: 7,
    name: 'Caja 12/u de aceite semisintetico',
    category: 'Lubricantes',
    price: 5,
    iva: 10.5,
    badge: '',
    brand: 'Shimaha',
    specs: ['Aceite para cadenas 1L', 'Caja 12 unidades', 'Semisintético'],
    image: '/fotos/aceite/CHAIN 1L.jpg',
    description: 'Ideal para cadenas de motosierras.'
  },


  // --- AIRE Y NEUMATICA ---
  {
    id: 8,
    name: 'Compresor de transmision directa ',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Compresores',
    price: 129,
    iva: 10.5,
    badge: '',
    brand: 'Shimaha',
    specs: ['2hp', '25L', 'Uso hogareño'],
    image: '/fotos/Aire y neumatica/WD-2025.jpg',
    description: 'Compresor de transmisión directa, caudal de 147 L/min y presion de 8 bar.'
  },
  {
    id: 9,
    name: 'Compresor transmisión directa',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Compresores',
    price: 117,
    iva: 10.5,
    badge: '',
    brand: 'Shimaha',
    specs: ['8bar', '2,5 hp', '50L', 'Uso hogareño'],
    image: '/fotos/Aire y neumatica/ZA-2050.jpg',
    description: 'Compresor de transmisión directa, caudal de 206 L/min a 8 bar de presión constante.'
  },
  {
    id: 10,
    name: 'Compresor transmisión directa',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Compresores',
    price: 140,
    iva: 10.5,
    badge: '',
    brand: 'Shimaha',
    specs: ['8bar', '2,5 hp', '50L', 'Uso hogareño'],
    image: '/fotos/Aire y neumatica/ZA-2050-K3.jpg',
    description: 'Compresor de transmisión directa, caudal de 206 L/min y presion de 8 bar. Incluye kit de 3 piezas'
  },
  {
    id: 11,
    name: 'Compresor de transmisión indirecta',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Compresores',
    price: 490,
    iva: 10.5,
    badge: '',
    brand: 'Shimaha',
    specs: ['3 hp', '100L', 'Uso intensivo'],
    image: '/fotos/Aire y neumatica/compresor1.jpg',
    description: 'Compresor de transmisión indirecto a correa, caudal de 310 L/min.'
  },
  {
    id: 12,
    name: 'Compresor de transmisión a correa',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Compresores',
    price: 589,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['3 hp', '150L', 'Uso intensivo'],
    image: '/fotos/Aire y neumatica/compresor2.jpg',
    description: 'Compresor de transmisión a correa, caudal de 310 L/min.'
  },
  {
    id: 13,
    name: 'Compresor de transmisión a correa',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Compresores',
    price: 764,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['5,5 hp', '100L', 'Uso intensivo'],
    image: '/fotos/Aire y neumatica/AMX-55100P.jpg',
    description: 'Compresor de transmisión a correa, caudal de 335 L/min.'
  },
  {
    id: 14,
    name: 'Compresor de transmisión a correa',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Compresores',
    price: 1030,
    iva: 10.5,
    badge: 'PROXIMAMENTE',
    brand: 'AMX',
    specs: ['5,5 hp', '300L', 'Uso intensivo'],
    image: '/fotos/Aire y neumatica/AMX-55300.jpg',
    description: 'Compresor de transmisión a correa, caudal de 580 L/min.'
  },
  {
    id: 15,
    name: 'Compresor de transmisión a correa',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Compresores',
    price: 1541,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['7,5 hp', '500L', 'Uso intensivo'],
    image: '/fotos/Aire y neumatica/AMX-75500.jpg',
    description: 'Compresor de transmisión a correa, caudal de 900 L/min.'
  },
  {
    id: 16,
    name: 'Llave de impacto neumática 1/2"',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 30,
    iva: 21,
    badge: '',
    brand: 'AMX',
    specs: ['1/2"', '400 Nm'],
    image: '/fotos/Aire y neumatica/AT-4070.jpg',
    description: 'Llave de impacto neumática 1/2" con doble martillo y torque maximo de 400 Nm.'
  },
  {
    id: 17,
    name: 'Taladro neumatico reversible',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 24,
    iva: 21,
    badge: '',
    brand: 'AMX',
    specs: ['3/8"'], 
    image: '/fotos/Aire y neumatica/AT-4031.jpg',
    description: 'Taladro neumático reversible de 3/8" (10 mm), compacto y liciano con peso de 1,2 kg.'
  },
  {
    id: 18,
    name: 'Pico de inflado de neumáticos',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 2.50,
    iva: 21,
    badge: '',
    brand: 'AMX',
    specs: [''],
    image: '/fotos/Aire y neumatica/AA-3065.jpg',
    description: 'Pico de inflado de neumáticos.'
  },
  {
    id: 19,
    name: 'Mini regulador',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 2.50,
    iva: 21,
    badge: '',
    brand: 'AMX',
    specs: [''],
    image: '/fotos/Aire y neumatica/AA-2006.jpg',
    description: 'Mini regulador neumatico, con conezion de 1/4", ideal para regular el flujo de aire.'
  },
  {
    id: 20,
    name: 'Union articulada neumatica',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 5,
    iva: 21,
    badge: '',
    brand: 'AMX',
    specs: [''],
    image: '/fotos/Aire y neumatica/AA-2005.jpg',
    description: 'Union articulada neumatica con conexion de 1/4", diseñada para facilitar conexiones flexibles.'
  },
  {
    id: 21,
    name: 'Filtro y regulador de aire',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 17,
    iva: 21,
    badge: '',
    brand: 'AMX',
    specs: [''],
    image: '/fotos/Aire y neumatica/AA-2027.jpg',
    description: 'Filtro y regulador de aire para controlar la presion y filtrar impurezas del sistema neumatico.'
  },
  {
    id: 22,
    name: 'Amoladora angular neumatica',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 50,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['Disco de 5"', '90 psi', '11.000 rpm', '2 Hp'],
    image: '/fotos/Aire y neumatica/AT-7037.jpg',
    description: 'Amoladora angular neumatica con disco de 5", presion de trabajo de 90 psi y consumo de 170 L/min.'
  },
  {
    id: 23,
    name: 'Amoladora recta neumatica',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 19,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['1.5 Hp', '90 psi'],
    image: '/fotos/Aire y neumatica/AT-7033K.jpg',
    description: 'Amoladora recta neumatica con boquilla de 1/4", consumo de 143 L/min y presion de trabajo de 90 psi.'
  },
  {
    id: 24,
    name: 'Amoladora recta neumatica',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 14,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['22.000rpm', '1.5 Hp', '90 psi'],
    image: '/fotos/Aire y neumatica/AT-7033.jpg',
    description: 'Amoladora recta neumatica con boquilla de 1/4", (6,35 mm), consumo de 143 L/min y presion de trabajo de 90 psi.'
  },
  {
    id: 25, 
    name: 'Amoladora recta neumatica',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 24,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['1,5 Hp', '90 psi' ],
    image: '/fotos/Aire y neumatica/AT-7033L.jpg',
    description: 'Amoladora recta neumatica con boquilla de 1/4", (6,35 mm), eje de 15cm, consumo de 143 L/min y presion de trabajo de 90 psi.'
  },
  {
    id: 26,
    name: 'Amoladora para gomeria y metal',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 37,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['1,5 Hp', '90 psi', '22.000 rpm'],
    image: '/fotos/Aire y neumatica/AT-6055.jpg',
    description: 'Amoladora para gomeria y metal con boquilla de 1/4", (6,35 mm), consumo de 140 L/min y presion de trabajo de 90 psi.'
  },
  {
    id: 27,
    name: 'Microamoladora neumatica',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 20,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['1,5 Hp', '90 psi'],
    image: '/fotos/Aire y neumatica/microamoladora.jpg',
    description: 'Microamoladora neumatica con presion de trabajo de 90 psi, incluye kit de piedra y lubricador.'
  },
  {
    id: 28,
    name: 'Martillo neumatico',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 28,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['3.000 impactos por minuto', '90 psi'],
    image: '/fotos/Aire y neumatica/AT-2020.jpg',
    description: 'Martillo neumatico de encastre redondo, 3.000 impactos por minuto, consumo de 157 L/min y presion de trabajo de 90 psi.'
  },
  {
    id: 29,
    name: 'Clavadora neumatica',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 30,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['90 psi', '2 Hp' ],
    image: '/fotos/Aire y neumatica/F-50.jpg',
    description: 'Clavadora neumatica para clavos de 1-25 mm, largo de 16-40 mm, presion de 90 psi y consumo de 1,13 L/disparo.'
  },
  {
    id: 30,
    name: 'Clavadora paletera',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 240,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['90 psi', '2 Hp' ],
    image: '/fotos/Aire y neumatica/CN90.jpg',
    description: 'Clavadora paletera para clavos de  0 2,8-38  mm, largo de 50-90 mm, presion de 90 psi y consumo de 1,13 L/disparo.'
  },
  {
    id: 31,
    name: 'Clavadora de palma',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 29,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['90 psi', '1.5 Hp' ],
    image: '/fotos/Aire y neumatica/AT-3100.jpg',
    description: 'Clavadora de palma para clavos tipo paris con presion de trabajo de 90 psi y consumo de 0,85 L/min.'
  },
  {
    id: 32,
    name:'Clavadora/grampadora neumatica',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 32,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['' ],
    image: '/fotos/Aire y neumatica/F-50 9040.jpg',
    description: 'Clavadora/grampadora neumatica para clavos de 1-25 mm, largo de 16-40 mm, y capacidad de 5,7 mm.'
  },
  {
    id: 33,
    name: 'Minicompresor',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 104,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['1/4 Hp', '200W', ],
    image: '/fotos/Aire y neumatica/AS-06K.jpg',
    description: 'Minicompresor con manguera reforzada, pìstola metalica y embudo de viscocidad.'
  },
  {
    id:34,
    name: 'Engrapadora neumatica',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 29,
    iva: 10.5,
    badge:'',
    brand:'AMX', 
    specs:[''],
    image:'/fotos/Aire y neumatica/8416.jpg',
    description:'Engrapadora neumatica para grampas de 12,8 mm de ancho, largo de 8-16mm y peso de 1,8Kg.'
  },
  {
    id:35,
    name: 'Engrapadora neumatica',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 28,
    iva: 10.5,
    badge:'',
    brand:'AMX', 
    specs:['90 psi'],
    image:'/fotos/Aire y neumatica/engrapadora.jpg',
    description:'Engrapadora neumatica con capacidad de 10,1 mm, largo de 8-14 mm, presion de trabajo de 90 psi y consumo de 0,11 L/disparo.'
  },
  {
    id:36,
    name: 'Engrapadora neumatica',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 26,
    iva: 10.5,
    badge:'',
    brand:'AMX', 
    specs:['2 Hp', '90 psi'],
    image:'/fotos/Aire y neumatica/9040.jpg',
    description:'Engrapadora neumatica con capacidad de 5,7 mm, largo de 16-40 mm, presion de trabajo de 90 psi y consumo de 0,11 L/disparo'
  },
  {
    id:37,
    name: 'Taladro angular',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 40,
    iva: 10.5,
    badge:'',
    brand:'AMX', 
    specs:['1800 rpm'],
    image:'/fotos/Aire y neumatica/AT-4036-6.jpg',
    description:'Taladro angular neumatico de hasta 10 mm, compacto y diseñado para trabajar en espacios reducidos'
  },
  {
    id:38,
    name: 'Taladro neumatico reversible',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 30,
    iva: 10.5,
    badge:'',
    brand: 'AMX', 
    specs:[''],
    image:'/fotos/Aire y neumatica/AT-4041.jpg',
    description:'Taladro neumatico reversible con mandril de 13 mm y mango de fuerza.'
  },
  {
    id:39,
    name: 'Atornillador neumatico',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 58,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['8.000 rpm', '1.5 Hp'],
    image:'/fotos/Aire y neumatica/AT-4060A.jpg',
    description:'Atornillador neumatico'
  },
  {
    id:40,
    name: 'Cortadora neumatica',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 15,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['22.000rpm', '1.5 Hp', '90 psi'],
    image:'/fotos/Aire y neumatica/cortadoraneumatica.jpg',
    description:'Cortadora neumatica de metales para discos de 3", consumo de 170 L/min y presion de trabajo de 90 psi'
  },
  {
    id:41,
    name: 'Equipo de pintar',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 24,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['600W'],
    image:'/fotos/Aire y neumatica/LL01.jpg',
    description:'Equipo de pintar con pistola plastica, accesorios incluidos y diseñado para uso hobbista'
  },
  {
    id:42,
    name: 'Equipo de pintar',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 56,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['600W'],
    image:'/fotos/Aire y neumatica/LL07.jpg',
    description:'Equipo de pintar con pistola metalica, apto para esmalte y laca para uso semiprofesional'
  },
  {
    id:43,
    name: 'Llave de impacto',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 30,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['7.000rpm', '2 Hp'],
    image:'/fotos/Aire y neumatica/AT-5040.jpg',
    description:'LLave de impacto neumatica, con encastre de 1/2", torque de 230 lb/pie y consumo de 0.22 m/min.'
  },
   {
    id:44,
    name: 'Kit de llave de impacto',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 43,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/AT-5004.jpg',
    description:'Kit de llave de impacto con estuche, 10 tubos de alto impacto, extension y minilubricador.'
  },
  {
    id:45,
    name: 'Llave de impacto',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 210,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['3.800rpm', '5 Hp'],
    image:'/fotos/Aire y neumatica/AT-6081.jpg',
    description:'Llave de impacto neumatica con encasre de 1", torque de 1.250 lb/pie y consumo de 1 L/min.'
  },
  {
    id:46,
    name: 'Llave de impacto',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 61,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['7.000rpm', '2 Hp'],
    image:'/fotos/Aire y neumatica/AT-5044.jpg',
    description:'Llave de impacto para uso industrial,con encastre de 1/2", torque de 370 lb/pie y consumo de 0,23 m/min.'
  },
  {
    id:47,
    name: 'Llave de impacto',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 134 ,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['4.500rpm', '3 Hp'],
    image:'/fotos/Aire y neumatica/AT-430-2.jpg',
    description:'Llave de impacto para uso pesado con encastre de 3/4", torque de 500lb/pie y consumo de 0,34 m/min.'
  },
  {
    id:48,
    name: 'Kit llave de impacto',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 29,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/AT-4007.jpg',
    description:'Kit de llave de impacto con 10 tubos de alto impacto, extension, minilubricador y estuche.'
  },
  {
    id:49,
    name: 'Lijadora de palma',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 34,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['10.000rpm', '2 Hp'],
    image:'/fotos/Aire y neumatica/SC 9806.jpg',
    description:'Lijadora de palma de 5", consumo de 170 L/min, presion de trabajo de 90psi, y bolsa recolectora.'
  },
  {
    id:50,
    name: 'Lijadora roto-orbital',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 27,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['10.000rpm', '2 Hp'],
    image:'/fotos/Aire y neumatica/AT-7015.jpg',
    description:'Lijadora roto-orbital, de 6", consumo de 170 L/min y presion de 90psi.'
  },
  {
    id:51,
    name: 'Lijadora orbital',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 28,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['8.000rpm'],
    image:'/fotos/Aire y neumatica/AT-7018.jpg',
    description:'Lijadora orbital de 175 x 95mm, compacta y liviana, con peso de 1,9kg.'
  },
  {
    id:52,
    name: 'Cizalla neumatica',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 31,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['2 Hp'],
    image:'/fotos/Aire y neumatica/AT-6021.jpg',
    description:'Cizalla neumatica, con capacidad de corte de 1,2mm.'
  },
  {
    id:53,
    name: 'Lijadora de banda',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 61,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['16.000rpm'],
    image:'/fotos/Aire y neumatica/AT-1038.jpg',
    description:'Lijadora de banda, con banda de 20x520 mm y consumo de 198 L/min.'
  },
  {
    id:54,
    name: 'Punzonadora',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 37,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['3.600rpm'],
    image:'/fotos/Aire y neumatica/AT-1503.jpg',
    description:'Punzonadora con corte en acero de 0,5-1,2mm y consumo de 141 L/min.'
  },
  {
    id:55,
    name: 'Lijadora de banda',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 55,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['18.000rpm'],
    image:'/fotos/Aire y neumatica/AT-1037.jpg',
    description:'Lijadora de banda con banda de 10x330mm y consumo de 113 L/min.'
  },
  {
    id:56,
    name: 'Lijadora orbital',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 43,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['15.000rpm'],
    image:'/fotos/Aire y neumatica/lijadoraorbital.jpg',
    description:'Lijadora orbital compacta de 2" y consumo de 84 L/min.'
  },
  {
    id:57,
    name: 'Escariadora',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 48,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/escariadora.jpg',
    description:'Escariadora con velocidad indicada en la pieza de 4.500 gpm y consumo de 113L/min.'
  },
  {
    id:58,
    name: 'sierra caladora',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 44,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['9.000rpm'],
    image:'/fotos/Aire y neumatica/AT-1600.jpg',
    description:'Sierra caladora con consumo de aire de 169L/min.'
  },
  {
    id:59,
    name: 'Pistola a succion para limpieza',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 9,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/pistolasuccion.jpg',
    description:'Pistola a succion diseñada para tareas de limpieza'
  },
  {
    id:60,
    name: 'Pistola baja presion',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 23,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['0,75L'],
    image:'/fotos/Aire y neumatica/S-112.jpg',
    description:'Pistola baja presion con boquilla estandar de 1,3mm, deposito metalico, consumo de 90-60 L/min. y presion de trabajo de 30-50psi.'
  },
  {
    id:61,
    name: 'Pistola de pintar alta presion',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 29,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/AS-1050.jpg',
    description:'Pistola de pintar alta presion, diseñada para trabajo de pintura con sistemas de alta presion.'
  },
  {
    id:62,
    name: 'Pistola alta/succion',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 40,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['6bar', '1L'],
    image:'/fotos/Aire y neumatica/4001SS.jpg',
    description:'Pistola alta/succion, boquilla estandar de 1,8mm y deposito metalico.'
  },
  {
    id:63,
    name: 'Pistola para pintar',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 18,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['3,4bar', '1L'],
    image:'/fotos/Aire y neumatica/AA-5001.jpg',
    description:'Pistola para pintar, deposito metalico, consumo de 120L/min. y presion de trabajo de 30.50psi.'
  },
  {
    id:64,
    name: 'Pistola de pintar HVLP',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 23,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['0,6L'],
    image:'/fotos/Aire y neumatica/AS-1004.jpg',
    description:'Pistola de pintar HVLP con deposito plastico.'
  },
  {
    id:65,
    name: 'Pistola de pintar baja/gravedad',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 25,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['3,4bar', '1L'],
    image:'/fotos/Aire y neumatica/AS-1005.jpg',
    description:'Pistola de pintar de baja/gravedad, boquilla estandar de 1,4mm, deposito metalico y consumo de 20L/min.'
  },
  {
    id:66,
    name: 'Pistola para inflar',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 12,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/AA-6000.jpg',
    description:'Pistola para inflar, permite inflar, desinflar y calibrar neumaticos e incluye manometro.'
  },
  {
    id:67,
    name: 'Pistola HVLP/gravedad',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 12,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['200cm3'],
    image:'/fotos/Aire y neumatica/K-3A.jpg',
    description:'Pistola HVLP/gravedad, boquilla estandar de 1,3mm, deposito metalico y consumo de 120 L/min.'
  },
  {
    id:68,
    name: 'Pistola alta/gravedad',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 19,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['0,4L'],
    image:'/fotos/Aire y neumatica/W-71G.jpg',
    description:'Pistola alta/gravedad, boquilla estandar de 1,5mm, deposito metalico y consumo de 230 L/min.'
  },
  {
    id:69,
    name: 'Pistola engrasadora',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 30,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['400 cm3'],
    image:'/fotos/Aire y neumatica/pistolaengrasadora.jpg',
    description:'Pistola engrasadora'
  },
  {
    id:70,
    name: 'Pistola para aplicar salpicre',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 28,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['6,2bar', '5L'],
    image:'/fotos/Aire y neumatica/AS-1082.jpg',
    description:'Pistola para aplicar salpicre por gravedad, boquilla estandar de 6mm, deposito de plastico de 5L y consumo de 350-430 L/min.'
  },
  {
    id:71,
    name: 'Aerografo neumatico',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 22,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/AB-1001.jpg',
    description:'Aerografo neumatico compacto y adecuado para trabajos de pintura y aplicaciones de precision.'
  },
  {
    id:72,
    name: 'Pistola arenadora',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 17,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/AA-3071.jpg',
    description:'Pistola arenadora, diseñada para limpieza y tratamiento de superficies mediante material abrasivo.'
  },
  {
    id:73,
    name: 'Pistola arenadora',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 23,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['6,2 bar'],
    image:'/fotos/Aire y neumatica/AA-3072.jpg',
    description:'Pistola arenadora, capacidad de 0,7Kg, presion de trabajo de 90psi, y manguera de ingreso de 1/4 NPT.'
  },
  {
    id:74,
    name: 'Pistola pulverizadora',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 6,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/SG-301.jpg',
    description:'Pistola pulverizadora metalica, diseñada para trabajos de pulverizacion a alta presion.'
  },
  {
    id:75,
    name: 'Aplicador de silicona reforzado',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 19,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/aplicadorsilicona.jpg',
    description:'Aplicador de silicona reforzado, consumo de 164 L/min y presion de trabajo de 90psi.'
  },
  {
    id:76,
    name: 'Pico para inflar dual',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 2.5,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['6,2 bar', '1,5 Hp'],
    image:'/fotos/Aire y neumatica/AA-3066.jpg',
    description:'Pico para infar dual, diseñado para faciliar el inflado de neumaticos con aire comprimido.'
  },
  {
    id:77,
    name: 'Regulador con medidor de 1/4"',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 10,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/AA-2001.jpg',
    description:'Regulador con medidor de 1/4", permite controlar y visualizar la presion del sistema de aie comprimdo.'
  },
  {
    id:78,
    name: 'Manguera espiralada de 1/4"',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 9,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/AA-1013.jpg',
    description:'Manguera espiralada de 1/4", con 15 metros de longitud para conexiones y herramientas neumaticas.' 
  },
  {
    id:79,
    name: 'Manguera PVC',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 23,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/PV-14.jpg',
    description:'Manguera PVC de 1/4", con una longitud total de 30 m.'
  },
  {
    id:80,
    name: 'Balanceador de herramientas',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 62,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/AA-2008S.jpg',
    description:'Balanceador de herramientas diseñado para soportar equipos de 0,6 a 2Kg.'
  },
  {
    id:81,
    name: 'Balanceador de herramientas',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 26,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/AA-2007S.jpg',
    description:'Balanceador de herramientas diseñado para soportar equipos de 3 a 5Kg.'
  },
  {
    id:82,
    name: 'Llave crique + accesorios',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 31,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['1600rpm', '6,2bar'],
    image:'/fotos/Aire y neumatica/AT-5002.jpg',
    description:'Llave crique + accesorios con encastre de 1/2", incluye 7 tubos de alto impacto prolongador y articulacion.'
  },
  {
    id:83,
    name: 'Llave crique',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 23,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['1600rpm', '6,2bar'],
    image:'/fotos/Aire y neumatica/AT-5053.jpg',
    description:'Llave crique con encastre de 1/2", torque de 50lbs/pie y consumo de 110 L/min.'
  },
  {
    id:84,
    name: 'Remachadora',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 54,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['6,2 bar'],
    image:'/fotos/Aire y neumatica/AT-6015.jpg',
    description:'Remachadora para remaches de 3,5  a 5mm, admite hasta 3/16" y tiene un consumo de aire de 19L/min.'
  },
  {
    id:84,
    name: 'Remachadora neumatica',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 32,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/AT-6013A.jpg',
    description:'Remachadora neumatica diseñada para trabajos de remachado mediante aire comprimido.'
  },
  {
    id:85,
    name: 'Filtro, regulador y lubricador',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 36,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/AA-2029.jpg',
    description:'Diseñado para acondicionar y regular el suministro de aire.'
  },
  {
    id:86,
    name: 'Filtro, regulador y lubricador',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 36,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/AA-2029-12.jpg',
    description:'Con conexion de 1/2", para sistemas de aire comprimido.'
  },
  {
    id:87,
    name: 'Mini lubricador 1/4"',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 4,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/AA-3040.jpg',
    description:'Diseñado para lubricar herramientas y sistemas neumaticos.'
  },
  {
    id:88,
    name: 'Drenador y trampa de agua',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 5,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/AA-2002.jpg',
    description:'De 1/4" ideal para separar la humedad del sistema de aire comprimido.'
  },
  {
    id:89,
    name: 'Herramienta multifuncion',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 35,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['180 rpm'],
    image:'/fotos/Aire y neumatica/AT-2033.jpg',
    description:'Apta para trabajos de lijado, corte y espatulado.'
  },


  // --- CONSTRUCCIÓN ---
  {
    id: 90,
    name: 'Carretilla',
    category: 'Construcción',
    subcategory:'Carretillas y palas',
    price: 61,
    iva: 10.5;
    badge: '',
    brand: 'OBRA',
    specs: ['150 Kg', '72L'],
    image: '/fotos/Construccion/CA 3150.jpg',
    description: 'Carretilla con tanque plastico de 0,7mm, rueda neumatica de 4x8".'
  },
  {
    id: 91,
    name: 'Carretilla',
    category: 'Construcción',
    subcategory:'Carretillas y palas',
    price: 61,
    iva: 10.5,
    badge: '',
    brand: 'OBRA',
    specs: ['150 Kg', '72L'],
    image: '/fotos/Construccion/CAM 3150.jpg',
    description: 'Carretilla con tanque metalico de 0,7mm, rueda neumatica de 4 x 8".'
  },
  {
    id: 92,
    name: 'Carretilla',
    category: 'Construcción',
    subcategory:'Carretillas y palas',
    price: 85,
    iva: 10.5,
    badge: '',
    brand: 'OBRA',
    specs: ['160 Kg', '120L'],
    image: '/fotos/Construccion/CAM 8160.jpg',
    description: 'Carretilla con tanque metalico de 0,9mm, rueda neumatica de 4 x 8".'
  },
  {
    id: 93,
    name: 'Carretilla',
    category: 'Construcción',
    subcategory:'Carretillas y palas',
    price: 878,
    iva: 10.5, 
    badge: '',
    brand: 'OBRA',
    specs: ['160 Kg', '120L'],
    image: '/fotos/Construccion/CAM 8160S.jpg',
    description: 'Carretilla con tanque metalico de 0,9mm, rueda solida de 4 x 8".'
  },
  {
    id: 94,
    name: 'Carretilla',
    category: 'Construcción',
    subcategory:'Carretillas y palas',
    price: 87,
    iva: 10.5,
    badge: '',
    brand: 'OBRA',
    specs: ['160 Kg', '120L'],
    image: '/fotos/Construccion/CA 8160.jpg',
    description: 'Carretilla con tanque plastico de 0,9mm, rueda de 4 x 8".'
  },
  {
    id: 95,
    name: 'Carretilla',
    category: 'Construcción',
    subcategory:'Carretillas y palas',
    price: 78,
    iva: 10.5,
    badge: '',
    brand: 'OBRA',
    specs: ['160 Kg', '120L'],
    image: '/fotos/Construccion/CA 8160S.jpg',
    description: 'Carretilla con tanque plastico de 0,9mm, rueda solida de 4 x 8".'
  },
  {
    id: 96,
    name: 'Pala ancha cuadrada',
    category: 'Construcción',
    subcategory:'Carretillas y palas',
    price: 8.65,
    iva: 10.5, 
    badge: '',
    brand: 'OBRA',
    specs: [''],
    image: '/fotos/Construccion/PAC300.jpg',
    description: 'Cabo de madera, mango laqueado con plastico y cabezal metalico de alta resistencia.'
  },
  {
    id: 97,
    name: 'Pala punta cuadrada',
    category: 'Construcción',
    subcategory:'Carretillas y palas',
    price: 8.65,
    iva: 10.5,
    badge: '',
    brand: 'OBRA',
    specs: [''],
    image: '/fotos/Construccion/PPC300.jpg',
    description: 'Cabo de madera, mango laqueado con plastico y cabezal metalico de alta resistencia.'
  },
  {
    id: 98,
    name: 'Pala punta cuadrada',
    category: 'Construcción',
    subcategory:'Carretillas y palas',
    price: 11.50,
    iva:10.5,
    badge: '',
    brand: 'OBRA',
    specs: [''],
    image: '/fotos/Construccion/PPC800.jpg',
    description: 'Cabo metalico, mango laqueado con plastico y cabezal metalico de alta resistencia.'
  },

  //MEZCLADORAS, ALISADORA Y COMPACTADORAS
  {
    id: 99,
    name: 'Mezcladora de hormigon',
    category: 'Construcción',
    subcategory:'Mezcladoras, Alisadoras y Compactadoras',
    price: 260,
    iva:10.5,
    badge: '',
    brand: 'OBRA',
    specs: ['550 W', '140L'],
    image: '/fotos/Construccion/MH 8140 25.jpg',
    description: 'Con tambor de 570mm y boca de 380mm. Tipo de aislacion clase 2.'
  },
   {
    id: 100,
    name: 'Mezcladora de hormigon',
    category: 'Construcción',
    subcategory:'Mezcladoras, Alisadoras y Compactadoras',
    price: 310,
    iva: 10.5,
    badge: '',
    brand: 'OBRA',
    specs: ['800 W', '180L'],
    image: '/fotos/Construccion/MH 8180 25.jog',
    description: 'Con tambor de 630mm y boca de 390mm. Tipo de aislacion clase 2.'
  },
   {
    id: 101,
    name: 'Compactor de empuje a gasolina',
    category: 'Construcción',
    subcategory:'Mezcladoras, Alisadoras y Compactadoras',
    price: 600,
    iva: 10.5,
    badge: '',
    brand: 'OBRA',
    specs: ['196cc', '6,5 Hp'],
    image: '/fotos/Construccion/CE1090.jpg',
    description: 'Fuerza centrifuga de 10Kn, profundidad de compactacion de 30cm y rendimiento de 750 m2/h.'
  },
   {
    id: 102,
    name: 'Compactadora de empuje a gasolina',
    category: 'Construcción',
    subcategory:'Mezcladoras, Alisadoras y Compactadoras',
    price: 1050,
    iva: 10.5,
    badge: '',
    brand: 'OBRA',
    specs: ['196 cc', '6 Hp'],
    image: '/fotos/Construccion/CE 10125.jpg',
    description: 'Fuerza centrifuga de 20 Kn, profundidad de compactacion de 30cm y rendimiento de 660 m2/h.'
  },
   {
    id: ,
    name: '',
    category: 'Construcción',
    subcategory:'Mezcladoras, Alisadoras y Compactadoras',
    price: ,
    iva:10.5,
    badge: '',
    brand: '',
    specs: [''],
    image: '/fotos/Construccion/',
    description: ''
  },

  // --- ENERGÍA ---
  {
    id: 10,
    name: 'Generador Naftero Shimaha 6.5 kW con Arranque',
    category: 'Energía',
    price: 1350000,
    badge: 'Esencial',
    brand: 'Shimaha',
    specs: ['Potencia 6.5 kW', 'Motor 16 HP 4T', 'Salida 220V', 'Batería incluida'],
    image: 'https://images.unsplash.com/photo-1513828583688-c52646db42da?w=800&auto=format&fit=crop&q=80',
    description: 'Generador profesional con regulación automática de voltaje (AVR), arranque eléctrico/manual, voltímetro y kit de ruedas de traslado.'
  }
];