const products = [
  // --- LUBRICANTES ---
{
    id: 1,
    name: 'Caja 12/u de aceite semisintetico 2T',
    category: 'Lubricantes',
    price: 7.25,
    iva: 10.5, // 10.5% 
    badge: '',
    brand: 'Shimaha',
    specs: ['Aceite 2T 1L', 'Caja 12 unidades', 'Semisintético'],
    image: '/fotos/Aceite/2TSS-1L.jpg',
    description: 'Ideal para uso intensivo en maquinas y herramientas de jardin.'
  },
  {
    id: 2,
    name: 'Caja 4/u de aceite semisintetico 2T',
    category: 'Lubricantes',
    price: 20.00,
    iva: 10.5,
    badge: '',
    brand: 'Shimaha',
    specs: ['Aceite 2T 4L', 'Caja 4 unidades', 'Semisintético'],
    image: '/fotos/Aceite/2TSS 4L.jpg',
    description: 'Ideal para uso intensivo en maquinas y herramientas de jardin.'
  },
  {
    id: 3,
    name: 'Aceite Semisintético 2T',
    category: 'Lubricantes',
    price: 604.35,
    iva: 10.5,
    badge: '',
    brand: 'Shimaha',
    specs: ['Aceite 2T 200L', 'Semisintético'],
    image: '/fotos/Aceite/2TSS-200L.jpg',
    description: 'Ideal para uso intensivo en maquinas y herramientas de jardin.'
  },
  {
    id: 4,
    name: 'Caja 24/u de aceite semisintetico 2T',
    category: 'Lubricantes',
    price: 1.45,
    iva: 10.5,
    badge: '',
    brand: 'Shimaha',
    specs: ['Aceite 2T 100cc', 'Caja 24 unidades', 'Semisintético'],
    image: '/fotos/aceite/2TSS-100cc.jpg',
    description: 'Ideal para uso intensivo en maquinas y herramientas de jardin.'
  },
  {
    id: 5,
    name: 'Caja 12/u de aceite semisintetico 4T',
    category: 'Lubricantes',
    price: 5.40,
    iva: 10.5,
    badge: '',
    brand: 'Shimaha',
    specs: ['Aceite 4T 1L', 'Caja 12 unidades', 'Semisintético'],
    image: '/fotos/aceite/4TSAE-1L.jpg',
    description: 'Ideal para uso intensivo en maquinas y herramientas de jardin.'
  },
  {
    id: 6,
    name: 'Aceite Semisintético 4T',
    category: 'Lubricantes',
    price: 558.45,
    iva: 10.5,
    badge: '',
    brand: 'Shimaha',
    specs: ['Aceite 4T 200L', 'Semisintético'],
    image: '/fotos/aceite/4TSAE-200L.jpg',
    description: 'Ideal para uso intensivo en maquinas y herramientas de jardin.'
  },
  {
    id: 7,
    name: 'Caja 12/u de aceite semisintetico',
    category: 'Lubricantes',
    price: 5,
    iva: 10.5,
    badge: '',
    brand: 'Shimaha',
    specs: ['Aceite para cadenas 1L', 'Caja 12 unidades', 'Semisintético'],
    image: '/fotos/aceite/CHAIN 1L.jpg',
    description: 'Ideal para cadenas de motosierras.'
  },


  // --- AIRE Y NEUMATICA ---
  {
    id: 8,
    name: 'Compresor de transmision directa ',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Compresores',
    price: 129,
    iva: 10.5,
    badge: '',
    brand: 'Shimaha',
    specs: ['2hp', '25L', 'Uso hogareño'],
    image: '/fotos/Aire y neumatica/WD-2025.jpg',
    description: 'Compresor de transmisión directa, caudal de 147 L/min y presion de 8 bar.'
  },
  {
    id: 9,
    name: 'Compresor transmisión directa',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Compresores',
    price: 117,
    iva: 10.5,
    badge: '',
    brand: 'Shimaha',
    specs: ['8bar', '2,5 hp', '50L', 'Uso hogareño'],
    image: '/fotos/Aire y neumatica/ZA-2050.jpg',
    description: 'Compresor de transmisión directa, caudal de 206 L/min a 8 bar de presión constante.'
  },
  {
    id: 10,
    name: 'Compresor transmisión directa',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Compresores',
    price: 140,
    iva: 10.5,
    badge: '',
    brand: 'Shimaha',
    specs: ['8bar', '2,5 hp', '50L', 'Uso hogareño'],
    image: '/fotos/Aire y neumatica/ZA-2050-K3.jpg',
    description: 'Compresor de transmisión directa, caudal de 206 L/min y presion de 8 bar. Incluye kit de 3 piezas'
  },
  {
    id: 11,
    name: 'Compresor de transmisión indirecta',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Compresores',
    price: 490,
    iva: 10.5,
    badge: '',
    brand: 'Shimaha',
    specs: ['3 hp', '100L', 'Uso intensivo'],
    image: '/fotos/Aire y neumatica/compresor1.jpg',
    description: 'Compresor de transmisión indirecto a correa, caudal de 310 L/min.'
  },
  {
    id: 12,
    name: 'Compresor de transmisión a correa',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Compresores',
    price: 589,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['3 hp', '150L', 'Uso intensivo'],
    image: '/fotos/Aire y neumatica/compresor2.jpg',
    description: 'Compresor de transmisión a correa, caudal de 310 L/min.'
  },
  {
    id: 13,
    name: 'Compresor de transmisión a correa',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Compresores',
    price: 764,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['5,5 hp', '100L', 'Uso intensivo'],
    image: '/fotos/Aire y neumatica/AMX-55100P.jpg',
    description: 'Compresor de transmisión a correa, caudal de 335 L/min.'
  },
  {
    id: 14,
    name: 'Compresor de transmisión a correa',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Compresores',
    price: 1030,
    iva: 10.5,
    badge: 'PROXIMAMENTE',
    brand: 'AMX',
    specs: ['5,5 hp', '300L', 'Uso intensivo'],
    image: '/fotos/Aire y neumatica/AMX-55300.jpg',
    description: 'Compresor de transmisión a correa, caudal de 580 L/min.'
  },
  {
    id: 15,
    name: 'Compresor de transmisión a correa',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Compresores',
    price: 1541,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['7,5 hp', '500L', 'Uso intensivo'],
    image: '/fotos/Aire y neumatica/AMX-75500.jpg',
    description: 'Compresor de transmisión a correa, caudal de 900 L/min.'
  },
  {
    id: 16,
    name: 'Llave de impacto neumática 1/2"',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 30,
    iva: 21,
    badge: '',
    brand: 'AMX',
    specs: ['1/2"', '400 Nm'],
    image: '/fotos/Aire y neumatica/AT-4070.jpg',
    description: 'Llave de impacto neumática 1/2" con doble martillo y torque maximo de 400 Nm.'
  },
  {
    id: 17,
    name: 'Taladro neumatico reversible',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 24,
    iva: 21,
    badge: '',
    brand: 'AMX',
    specs: ['3/8"'], 
    image: '/fotos/Aire y neumatica/AT-4031.jpg',
    description: 'Taladro neumático reversible de 3/8" (10 mm), compacto y liciano con peso de 1,2 kg.'
  },
  {
    id: 18,
    name: 'Pico de inflado de neumáticos',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 2.50,
    iva: 21,
    badge: '',
    brand: 'AMX',
    specs: [''],
    image: '/fotos/Aire y neumatica/AA-3065.jpg',
    description: 'Pico de inflado de neumáticos.'
  },
  {
    id: 19,
    name: 'Mini regulador',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 2.50,
    iva: 21,
    badge: '',
    brand: 'AMX',
    specs: [''],
    image: '/fotos/Aire y neumatica/AA-2006.jpg',
    description: 'Mini regulador neumatico, con conezion de 1/4", ideal para regular el flujo de aire.'
  },
  {
    id: 20,
    name: 'Union articulada neumatica',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 5,
    iva: 21,
    badge: '',
    brand: 'AMX',
    specs: [''],
    image: '/fotos/Aire y neumatica/AA-2005.jpg',
    description: 'Union articulada neumatica con conexion de 1/4", diseñada para facilitar conexiones flexibles.'
  },
  {
    id: 21,
    name: 'Filtro y regulador de aire',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 17,
    iva: 21,
    badge: '',
    brand: 'AMX',
    specs: [''],
    image: '/fotos/Aire y neumatica/AA-2027.jpg',
    description: 'Filtro y regulador de aire para controlar la presion y filtrar impurezas del sistema neumatico.'
  },
  {
    id: 22,
    name: 'Amoladora angular neumatica',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 50,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['Disco de 5"', '90 psi', '11.000 rpm', '2 Hp'],
    image: '/fotos/Aire y neumatica/AT-7037.jpg',
    description: 'Amoladora angular neumatica con disco de 5", presion de trabajo de 90 psi y consumo de 170 L/min.'
  },
  {
    id: 23,
    name: 'Amoladora recta neumatica',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 19,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['1.5 Hp', '90 psi'],
    image: '/fotos/Aire y neumatica/AT-7033K.jpg',
    description: 'Amoladora recta neumatica con boquilla de 1/4", consumo de 143 L/min y presion de trabajo de 90 psi.'
  },
  {
    id: 24,
    name: 'Amoladora recta neumatica',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 14,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['22.000rpm', '1.5 Hp', '90 psi'],
    image: '/fotos/Aire y neumatica/AT-7033.jpg',
    description: 'Amoladora recta neumatica con boquilla de 1/4", (6,35 mm), consumo de 143 L/min y presion de trabajo de 90 psi.'
  },
  {
    id: 25, 
    name: 'Amoladora recta neumatica',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 24,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['1,5 Hp', '90 psi' ],
    image: '/fotos/Aire y neumatica/AT-7033L.jpg',
    description: 'Amoladora recta neumatica con boquilla de 1/4", (6,35 mm), eje de 15cm, consumo de 143 L/min y presion de trabajo de 90 psi.'
  },
  {
    id: 26,
    name: 'Amoladora para gomeria y metal',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 37,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['1,5 Hp', '90 psi', '22.000 rpm'],
    image: '/fotos/Aire y neumatica/AT-6055.jpg',
    description: 'Amoladora para gomeria y metal con boquilla de 1/4", (6,35 mm), consumo de 140 L/min y presion de trabajo de 90 psi.'
  },
  {
    id: 27,
    name: 'Microamoladora neumatica',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 20,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['1,5 Hp', '90 psi'],
    image: '/fotos/Aire y neumatica/microamoladora.jpg',
    description: 'Microamoladora neumatica con presion de trabajo de 90 psi, incluye kit de piedra y lubricador.'
  },
  {
    id: 28,
    name: 'Martillo neumatico',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 28,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['3.000 impactos por minuto', '90 psi'],
    image: '/fotos/Aire y neumatica/AT-2020.jpg',
    description: 'Martillo neumatico de encastre redondo, 3.000 impactos por minuto, consumo de 157 L/min y presion de trabajo de 90 psi.'
  },
  {
    id: 29,
    name: 'Clavadora neumatica',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 30,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['90 psi', '2 Hp' ],
    image: '/fotos/Aire y neumatica/F-50.jpg',
    description: 'Clavadora neumatica para clavos de 1-25 mm, largo de 16-40 mm, presion de 90 psi y consumo de 1,13 L/disparo.'
  },
  {
    id: 30,
    name: 'Clavadora paletera',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 240,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['90 psi', '2 Hp' ],
    image: '/fotos/Aire y neumatica/CN90.jpg',
    description: 'Clavadora paletera para clavos de  0 2,8-38  mm, largo de 50-90 mm, presion de 90 psi y consumo de 1,13 L/disparo.'
  },
  {
    id: 31,
    name: 'Clavadora de palma',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 29,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['90 psi', '1.5 Hp' ],
    image: '/fotos/Aire y neumatica/AT-3100.jpg',
    description: 'Clavadora de palma para clavos tipo paris con presion de trabajo de 90 psi y consumo de 0,85 L/min.'
  },
  {
    id: 32,
    name:'Clavadora/grampadora neumatica',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 32,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['' ],
    image: '/fotos/Aire y neumatica/F-50 9040.jpg',
    description: 'Clavadora/grampadora neumatica para clavos de 1-25 mm, largo de 16-40 mm, y capacidad de 5,7 mm.'
  },
  {
    id: 33,
    name: 'Minicompresor',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 104,
    iva: 10.5,
    badge: '',
    brand: 'AMX',
    specs: ['1/4 Hp', '200W', ],
    image: '/fotos/Aire y neumatica/AS-06K.jpg',
    description: 'Minicompresor con manguera reforzada, pìstola metalica y embudo de viscocidad.'
  },
  {
    id:34,
    name: 'Engrapadora neumatica',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 29,
    iva: 10.5,
    badge:'',
    brand:'AMX', 
    specs:[''],
    image:'/fotos/Aire y neumatica/8416.jpg',
    description:'Engrapadora neumatica para grampas de 12,8 mm de ancho, largo de 8-16mm y peso de 1,8Kg.'
  },
  {
    id:35,
    name: 'Engrapadora neumatica',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 28,
    iva: 10.5,
    badge:'',
    brand:'AMX', 
    specs:['90 psi'],
    image:'/fotos/Aire y neumatica/engrapadora.jpg',
    description:'Engrapadora neumatica con capacidad de 10,1 mm, largo de 8-14 mm, presion de trabajo de 90 psi y consumo de 0,11 L/disparo.'
  },
  {
    id:36,
    name: 'Engrapadora neumatica',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 26,
    iva: 10.5,
    badge:'',
    brand:'AMX', 
    specs:['2 Hp', '90 psi'],
    image:'/fotos/Aire y neumatica/9040.jpg',
    description:'Engrapadora neumatica con capacidad de 5,7 mm, largo de 16-40 mm, presion de trabajo de 90 psi y consumo de 0,11 L/disparo'
  },
  {
    id:37,
    name: 'Taladro angular',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 40,
    iva: 10.5,
    badge:'',
    brand:'AMX', 
    specs:['1800 rpm'],
    image:'/fotos/Aire y neumatica/AT-4036-6.jpg',
    description:'Taladro angular neumatico de hasta 10 mm, compacto y diseñado para trabajar en espacios reducidos'
  },
  {
    id:38,
    name: 'Taladro neumatico reversible',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 30,
    iva: 10.5,
    badge:'',
    brand: 'AMX', 
    specs:[''],
    image:'/fotos/Aire y neumatica/AT-4041.jpg',
    description:'Taladro neumatico reversible con mandril de 13 mm y mango de fuerza.'
  },
  {
    id:39,
    name: 'Atornillador neumatico',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 58,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['8.000 rpm', '1.5 Hp'],
    image:'/fotos/Aire y neumatica/AT-4060A.jpg',
    description:'Atornillador neumatico'
  },
  {
    id:40,
    name: 'Cortadora neumatica',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 15,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['22.000rpm', '1.5 Hp', '90 psi'],
    image:'/fotos/Aire y neumatica/cortadoraneumatica.jpg',
    description:'Cortadora neumatica de metales para discos de 3", consumo de 170 L/min y presion de trabajo de 90 psi'
  },
  {
    id:41,
    name: 'Equipo de pintar',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 24,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['600W'],
    image:'/fotos/Aire y neumatica/LL01.jpg',
    description:'Equipo de pintar con pistola plastica, accesorios incluidos y diseñado para uso hobbista'
  },
  {
    id:42,
    name: 'Equipo de pintar',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 56,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['600W'],
    image:'/fotos/Aire y neumatica/LL07.jpg',
    description:'Equipo de pintar con pistola metalica, apto para esmalte y laca para uso semiprofesional'
  },
  {
    id:43,
    name: 'Llave de impacto',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 30,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['7.000rpm', '2 Hp'],
    image:'/fotos/Aire y neumatica/AT-5040.jpg',
    description:'LLave de impacto neumatica, con encastre de 1/2", torque de 230 lb/pie y consumo de 0.22 m/min.'
  },
   {
    id:44,
    name: 'Kit de llave de impacto',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 43,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/AT-5004.jpg',
    description:'Kit de llave de impacto con estuche, 10 tubos de alto impacto, extension y minilubricador.'
  },
  {
    id:45,
    name: 'Llave de impacto',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 210,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['3.800rpm', '5 Hp'],
    image:'/fotos/Aire y neumatica/AT-6081.jpg',
    description:'Llave de impacto neumatica con encasre de 1", torque de 1.250 lb/pie y consumo de 1 L/min.'
  },
  {
    id:46,
    name: 'Llave de impacto',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 61,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['7.000rpm', '2 Hp'],
    image:'/fotos/Aire y neumatica/AT-5044.jpg',
    description:'Llave de impacto para uso industrial,con encastre de 1/2", torque de 370 lb/pie y consumo de 0,23 m/min.'
  },
  {
    id:47,
    name: 'Llave de impacto',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 134 ,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['4.500rpm', '3 Hp'],
    image:'/fotos/Aire y neumatica/AT-430-2.jpg',
    description:'Llave de impacto para uso pesado con encastre de 3/4", torque de 500lb/pie y consumo de 0,34 m/min.'
  },
  {
    id:48,
    name: 'Kit llave de impacto',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 29,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/AT-4007.jpg',
    description:'Kit de llave de impacto con 10 tubos de alto impacto, extension, minilubricador y estuche.'
  },
  {
    id:49,
    name: 'Lijadora de palma',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 34,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['10.000rpm', '2 Hp'],
    image:'/fotos/Aire y neumatica/SC 9806.jpg',
    description:'Lijadora de palma de 5", consumo de 170 L/min, presion de trabajo de 90psi, y bolsa recolectora.'
  },
  {
    id:50,
    name: 'Lijadora roto-orbital',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 27,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['10.000rpm', '2 Hp'],
    image:'/fotos/Aire y neumatica/AT-7015.jpg',
    description:'Lijadora roto-orbital, de 6", consumo de 170 L/min y presion de 90psi.'
  },
  {
    id:51,
    name: 'Lijadora orbital',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 28,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['8.000rpm'],
    image:'/fotos/Aire y neumatica/AT-7018.jpg',
    description:'Lijadora orbital de 175 x 95mm, compacta y liviana, con peso de 1,9kg.'
  },
  {
    id:52,
    name: 'Cizalla neumatica',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 31,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['2 Hp'],
    image:'/fotos/Aire y neumatica/AT-6021.jpg',
    description:'Cizalla neumatica, con capacidad de corte de 1,2mm.'
  },
  {
    id:53,
    name: 'Lijadora de banda',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 61,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['16.000rpm'],
    image:'/fotos/Aire y neumatica/AT-1038.jpg',
    description:'Lijadora de banda, con banda de 20x520 mm y consumo de 198 L/min.'
  },
  {
    id:54,
    name: 'Punzonadora',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 37,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['3.600rpm'],
    image:'/fotos/Aire y neumatica/AT-1503.jpg',
    description:'Punzonadora con corte en acero de 0,5-1,2mm y consumo de 141 L/min.'
  },
  {
    id:55,
    name: 'Lijadora de banda',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 55,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['18.000rpm'],
    image:'/fotos/Aire y neumatica/AT-1037.jpg',
    description:'Lijadora de banda con banda de 10x330mm y consumo de 113 L/min.'
  },
  {
    id:56,
    name: 'Lijadora orbital',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 43,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['15.000rpm'],
    image:'/fotos/Aire y neumatica/lijadoraorbital.jpg',
    description:'Lijadora orbital compacta de 2" y consumo de 84 L/min.'
  },
  {
    id:57,
    name: 'Escariadora',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 48,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/escariadora.jpg',
    description:'Escariadora con velocidad indicada en la pieza de 4.500 gpm y consumo de 113L/min.'
  },
  {
    id:58,
    name: 'sierra caladora',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 44,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['9.000rpm'],
    image:'/fotos/Aire y neumatica/AT-1600.jpg',
    description:'Sierra caladora con consumo de aire de 169L/min.'
  },
  {
    id:59,
    name: 'Pistola a succion para limpieza',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 9,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/pistolasuccion.jpg',
    description:'Pistola a succion diseñada para tareas de limpieza'
  },
  {
    id:60,
    name: 'Pistola baja presion',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 23,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['0,75L'],
    image:'/fotos/Aire y neumatica/S-112.jpg',
    description:'Pistola baja presion con boquilla estandar de 1,3mm, deposito metalico, consumo de 90-60 L/min. y presion de trabajo de 30-50psi.'
  },
  {
    id:61,
    name: 'Pistola de pintar alta presion',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 29,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/AS-1050.jpg',
    description:'Pistola de pintar alta presion, diseñada para trabajo de pintura con sistemas de alta presion.'
  },
  {
    id:62,
    name: 'Pistola alta/succion',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 40,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['6bar', '1L'],
    image:'/fotos/Aire y neumatica/4001SS.jpg',
    description:'Pistola alta/succion, boquilla estandar de 1,8mm y deposito metalico.'
  },
  {
    id:63,
    name: 'Pistola para pintar',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 18,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['3,4bar', '1L'],
    image:'/fotos/Aire y neumatica/AA-5001.jpg',
    description:'Pistola para pintar, deposito metalico, consumo de 120L/min. y presion de trabajo de 30.50psi.'
  },
  {
    id:64,
    name: 'Pistola de pintar HVLP',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 23,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['0,6L'],
    image:'/fotos/Aire y neumatica/AS-1004.jpg',
    description:'Pistola de pintar HVLP con deposito plastico.'
  },
  {
    id:65,
    name: 'Pistola de pintar baja/gravedad',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 25,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['3,4bar', '1L'],
    image:'/fotos/Aire y neumatica/AS-1005.jpg',
    description:'Pistola de pintar de baja/gravedad, boquilla estandar de 1,4mm, deposito metalico y consumo de 20L/min.'
  },
  {
    id:66,
    name: 'Pistola para inflar',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 12,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/AA-6000.jpg',
    description:'Pistola para inflar, permite inflar, desinflar y calibrar neumaticos e incluye manometro.'
  },
  {
    id:67,
    name: 'Pistola HVLP/gravedad',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 12,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['200cm3'],
    image:'/fotos/Aire y neumatica/K-3A.jpg',
    description:'Pistola HVLP/gravedad, boquilla estandar de 1,3mm, deposito metalico y consumo de 120 L/min.'
  },
  {
    id:68,
    name: 'Pistola alta/gravedad',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 19,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['0,4L'],
    image:'/fotos/Aire y neumatica/W-71G.jpg',
    description:'Pistola alta/gravedad, boquilla estandar de 1,5mm, deposito metalico y consumo de 230 L/min.'
  },
  {
    id:69,
    name: 'Pistola engrasadora',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 30,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['400 cm3'],
    image:'/fotos/Aire y neumatica/pistolaengrasadora.jpg',
    description:'Pistola engrasadora'
  },
  {
    id:70,
    name: 'Pistola para aplicar salpicre',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 28,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['6,2bar', '5L'],
    image:'/fotos/Aire y neumatica/AS-1082.jpg',
    description:'Pistola para aplicar salpicre por gravedad, boquilla estandar de 6mm, deposito de plastico de 5L y consumo de 350-430 L/min.'
  },
  {
    id:71,
    name: 'Aerografo neumatico',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 22,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/AB-1001.jpg',
    description:'Aerografo neumatico compacto y adecuado para trabajos de pintura y aplicaciones de precision.'
  },
  {
    id:72,
    name: 'Pistola arenadora',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 17,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/AA-3071.jpg',
    description:'Pistola arenadora, diseñada para limpieza y tratamiento de superficies mediante material abrasivo.'
  },
  {
    id:73,
    name: 'Pistola arenadora',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 23,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['6,2 bar'],
    image:'/fotos/Aire y neumatica/AA-3072.jpg',
    description:'Pistola arenadora, capacidad de 0,7Kg, presion de trabajo de 90psi, y manguera de ingreso de 1/4 NPT.'
  },
  {
    id:74,
    name: 'Pistola pulverizadora',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 6,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/SG-301.jpg',
    description:'Pistola pulverizadora metalica, diseñada para trabajos de pulverizacion a alta presion.'
  },
  {
    id:75,
    name: 'Aplicador de silicona reforzado',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 19,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/aplicadorsilicona.jpg',
    description:'Aplicador de silicona reforzado, consumo de 164 L/min y presion de trabajo de 90psi.'
  },
  {
    id:76,
    name: 'Pico para inflar dual',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 2.5,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['6,2 bar', '1,5 Hp'],
    image:'/fotos/Aire y neumatica/AA-3066.jpg',
    description:'Pico para infar dual, diseñado para faciliar el inflado de neumaticos con aire comprimido.'
  },
  {
    id:77,
    name: 'Regulador con medidor de 1/4"',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 10,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/AA-2001.jpg',
    description:'Regulador con medidor de 1/4", permite controlar y visualizar la presion del sistema de aie comprimdo.'
  },
  {
    id:78,
    name: 'Manguera espiralada de 1/4"',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 9,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/AA-1013.jpg',
    description:'Manguera espiralada de 1/4", con 15 metros de longitud para conexiones y herramientas neumaticas.' 
  },
  {
    id:79,
    name: 'Manguera PVC',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 23,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/PV-14.jpg',
    description:'Manguera PVC de 1/4", con una longitud total de 30 m.'
  },
  {
    id:80,
    name: 'Balanceador de herramientas',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 62,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/AA-2008S.jpg',
    description:'Balanceador de herramientas diseñado para soportar equipos de 0,6 a 2Kg.'
  },
  {
    id:81,
    name: 'Balanceador de herramientas',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 26,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/AA-2007S.jpg',
    description:'Balanceador de herramientas diseñado para soportar equipos de 3 a 5Kg.'
  },
  {
    id:82,
    name: 'Llave crique + accesorios',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 31,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['1600rpm', '6,2bar'],
    image:'/fotos/Aire y neumatica/AT-5002.jpg',
    description:'Llave crique + accesorios con encastre de 1/2", incluye 7 tubos de alto impacto prolongador y articulacion.'
  },
  {
    id:83,
    name: 'Llave crique',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 23,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['1600rpm', '6,2bar'],
    image:'/fotos/Aire y neumatica/AT-5053.jpg',
    description:'Llave crique con encastre de 1/2", torque de 50lbs/pie y consumo de 110 L/min.'
  },
  {
    id:84,
    name: 'Remachadora',
    category: 'Aire Comprimido/Neuemática',
    subcategory: 'Herramientas Neumáticas',
    price: 54,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['6,2 bar'],
    image:'/fotos/Aire y neumatica/AT-6015.jpg',
    description:'Remachadora para remaches de 3,5  a 5mm, admite hasta 3/16" y tiene un consumo de aire de 19L/min.'
  },
  {
    id:84,
    name: 'Remachadora neumatica',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 32,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/AT-6013A.jpg',
    description:'Remachadora neumatica diseñada para trabajos de remachado mediante aire comprimido.'
  },
  {
    id:85,
    name: 'Filtro, regulador y lubricador',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 36,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/AA-2029.jpg',
    description:'Diseñado para acondicionar y regular el suministro de aire.'
  },
  {
    id:86,
    name: 'Filtro, regulador y lubricador',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 36,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/AA-2029-12.jpg',
    description:'Con conexion de 1/2", para sistemas de aire comprimido.'
  },
  {
    id:87,
    name: 'Mini lubricador 1/4"',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 4,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/AA-3040.jpg',
    description:'Diseñado para lubricar herramientas y sistemas neumaticos.'
  },
  {
    id:88,
    name: 'Drenador y trampa de agua',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 5,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:[''],
    image:'/fotos/Aire y neumatica/AA-2002.jpg',
    description:'De 1/4" ideal para separar la humedad del sistema de aire comprimido.'
  },
  {
    id:89,
    name: 'Herramienta multifuncion',
    category: 'Aire Comprimido/Neumática',
    subcategory: 'Herramientas Neumáticas',
    price: 35,
    iva: 10.5,
    badge:'', 
    brand:'AMX',
    specs:['180 rpm'],
    image:'/fotos/Aire y neumatica/AT-2033.jpg',
    description:'Apta para trabajos de lijado, corte y espatulado.'
  },


  // --- CONSTRUCCIÓN ---
  {
    id: 90,
    name: 'Carretilla',
    category: 'Construcción',
    subcategory:'Carretillas y palas',
    price: 61,
    iva: 10.5,
    badge: '',
    brand: 'OBRA',
    specs: ['150 Kg', '72L'],
    image: '/fotos/Construccion/CA 3150.jpg',
    description: 'Carretilla con tanque plastico de 0,7mm, rueda neumatica de 4x8".'
  },
  {
    id: 91,
    name: 'Carretilla',
    category: 'Construcción',
    subcategory:'Carretillas y palas',
    price: 61,
    iva: 10.5,
    badge: '',
    brand: 'OBRA',
    specs: ['150 Kg', '72L'],
    image: '/fotos/Construccion/CAM 3150.jpg',
    description: 'Carretilla con tanque metalico de 0,7mm, rueda neumatica de 4 x 8".'
  },
  {
    id: 92,
    name: 'Carretilla',
    category: 'Construcción',
    subcategory:'Carretillas y palas',
    price: 85,
    iva: 10.5,
    badge: '',
    brand: 'OBRA',
    specs: ['160 Kg', '120L'],
    image: '/fotos/Construccion/CAM 8160.jpg',
    description: 'Carretilla con tanque metalico de 0,9mm, rueda neumatica de 4 x 8".'
  },
  {
    id: 93,
    name: 'Carretilla',
    category: 'Construcción',
    subcategory:'Carretillas y palas',
    price: 878,
    iva: 10.5, 
    badge: '',
    brand: 'OBRA',
    specs: ['160 Kg', '120L'],
    image: '/fotos/Construccion/CAM 8160S.jpg',
    description: 'Carretilla con tanque metalico de 0,9mm, rueda solida de 4 x 8".'
  },
  {
    id: 94,
    name: 'Carretilla',
    category: 'Construcción',
    subcategory:'Carretillas y palas',
    price: 87,
    iva: 10.5,
    badge: '',
    brand: 'OBRA',
    specs: ['160 Kg', '120L'],
    image: '/fotos/Construccion/CA 8160.jpg',
    description: 'Carretilla con tanque plastico de 0,9mm, rueda de 4 x 8".'
  },
  {
    id: 95,
    name: 'Carretilla',
    category: 'Construcción',
    subcategory:'Carretillas y palas',
    price: 78,
    iva: 10.5,
    badge: '',
    brand: 'OBRA',
    specs: ['160 Kg', '120L'],
    image: '/fotos/Construccion/CA 8160S.jpg',
    description: 'Carretilla con tanque plastico de 0,9mm, rueda solida de 4 x 8".'
  },
  {
    id: 96,
    name: 'Pala ancha cuadrada',
    category: 'Construcción',
    subcategory:'Carretillas y palas',
    price: 8.65,
    iva: 10.5, 
    badge: '',
    brand: 'OBRA',
    specs: [''],
    image: '/fotos/Construccion/PAC300.jpg',
    description: 'Cabo de madera, mango laqueado con plastico y cabezal metalico de alta resistencia.'
  },
  {
    id: 97,
    name: 'Pala punta cuadrada',
    category: 'Construcción',
    subcategory:'Carretillas y palas',
    price: 8.65,
    iva: 10.5,
    badge: '',
    brand: 'OBRA',
    specs: [''],
    image: '/fotos/Construccion/PPC300.jpg',
    description: 'Cabo de madera, mango laqueado con plastico y cabezal metalico de alta resistencia.'
  },
  {
    id: 98,
    name: 'Pala punta cuadrada',
    category: 'Construcción',
    subcategory:'Carretillas y palas',
    price: 11.50,
    iva:10.5,
    badge: '',
    brand: 'OBRA',
    specs: [''],
    image: '/fotos/Construccion/PPC800.jpg',
    description: 'Cabo metalico, mango laqueado con plastico y cabezal metalico de alta resistencia.'
  },

  //MEZCLADORAS, ALISADORA Y COMPACTADORAS
  {
    id: 99,
    name: 'Mezcladora de hormigon',
    category: 'Construcción',
    subcategory:'Mezcladoras, Alisadoras y Compactadoras',
    price: 260,
    iva:10.5,
    badge: '',
    brand: 'OBRA',
    specs: ['550 W', '140L'],
    image: '/fotos/Construccion/MH 8140 25.jpg',
    description: 'Con tambor de 570mm y boca de 380mm. Tipo de aislacion clase 2.'
  },
  {
    id: 100,
    name: 'Mezcladora de hormigon',
    category: 'Construcción',
    subcategory:'Mezcladoras, Alisadoras y Compactadoras',
    price: 310,
    iva: 10.5,
    badge: '',
    brand: 'OBRA',
    specs: ['800 W', '180L'],
    image: '/fotos/Construccion/MH 8180 25.jpg',
    description: 'Con tambor de 630mm y boca de 390mm. Tipo de aislacion clase 2.'
  },
  {
    id: 101,
    name: 'Compactor de empuje a gasolina',
    category: 'Construcción',
    subcategory:'Mezcladoras, Alisadoras y Compactadoras',
    price: 600,
    iva: 10.5,
    badge: '',
    brand: 'OBRA',
    specs: ['196cc', '6,5 Hp'],
    image: '/fotos/Construccion/CE 1090.jpg',
    description: 'Fuerza centrifuga de 10Kn, profundidad de compactacion de 30cm y rendimiento de 750 m2/h.'
  },
  {
    id: 102,
    name: 'Compactadora de empuje a gasolina',
    category: 'Construcción',
    subcategory:'Mezcladoras, Alisadoras y Compactadoras',
    price: 1050,
    iva: 10.5,
    badge: '',
    brand: 'OBRA',
    specs: ['196 cc', '6 Hp'],
    image: '/fotos/Construccion/CE 10125.jpg',
    description: 'Fuerza centrifuga de 20 Kn, profundidad de compactacion de 30cm y rendimiento de 660 m2/h.'
  },
  {
    id: 103,
    name: 'Cortadora de concreto a gasolina',
    category: 'Construcción',
    subcategory:'Mezcladoras, Alisadoras y Compactadoras',
    price: 1000,
    iva:10.5,
    badge: '',
    brand: 'OBRA',
    specs: ['389 cc', '14 Hp', '40L'],
    image: '/fotos/Construccion/CC 1019.jpg',
    description: 'Con profundidad maxima de corte de 190mm, compatible con hojas de 350-500mm.'
  },
  {
    id: 104,
    name: 'Alisadora de concreto a gasolina',
    category: 'Construcción',
    subcategory:'Mezcladoras, Alisadoras y Compactadoras',
    price: 660,
    iva:10.5,
    badge: '',
    brand: 'OBRA',
    specs: ['6,5 Hp', '196cc'],
    image: '/fotos/Construccion/AC 1024.jpg',
    description: 'Con llana de 600mm(24"), hoja de 230 x 120mm, velocidad de 60-100 rpm e inclinacion regulable de 0º a 15º.'
  },

  
  

  // --- ENERGÍA ---
  {
    id: 105,
    name: 'Grupo electrogeno',
    category: 'Energía y Potencia',
    subcategory: 'Generadores y Grupos Electrogenos',
    price: 8950,
    iva: 10.5,
    badge: '',
    brand: 'Shimaha',
    specs: ['42 kVa', '80L'],
    image: '/fotos/Energia y potencia/SH-LG31X.jpg',
    description: 'De 39 KVA de potencia media, con salida 380/220 V, frecuencia de 50Hz, conexion trifasica 3P 4W en estrella y factor de potencia 0,8.'
  },
  {
    id: 106,
    name: 'Grupo electrogeno',
    category: 'Energia y Potencia',
    subcategory: 'Generadores y Grupos Electrogenos',
    price: 0,
    iva:10.5,
    badge: '',
    brand: 'Shimaha',
    specs: ['23 kVa', '80L'],
    image: '/fotos/Energia y Potencia/SH-LG16X.jpg',
    description: 'De 20 KVA de potencia media, con salida 380/220 V, frecuencia de 50Hz, conexion trifasica 3P 4W en estrella y factor de potencia 0,8.'
  },
  {
    id: 107,
    name: 'Tablero automatico',
    category: 'Energia y Potencia',
    subcategory: 'Generadores y Grupos Electrogenos',
    price: 0,
    iva:10.5,
    badge: '',
    brand: 'Shimaha',
    specs: [''],
    image: '/fotos/Energia y Potencia/SH-ATSLG16X.jpg',
    description: 'Para grupo electrogeno SH-LG16X con peso de 24,7Kg.'
  },
  {
    id: 108,
    name: 'Generador a gas natural',
    category: 'Energia y Potencia',
    subcategory: 'Generadores y Grupos Electrogenos',
    price: 0,
    iva:10.5,
    badge: '',
    brand: 'Shimaha',
    specs: ['16 Hp', '6,5kW'],
    image: '/fotos/Energia y Potencia/PT7500DEW-G.jpg',
    description: 'Envasado o nafta, con motor simil Honda, arranque manual/electrico y salida de 220V.'
  },
  {
    id: 109,
    name: 'Generador electrico',
    category: 'Energia y Potencia',
    subcategory: 'Generadores y Grupos Electrogenos',
    price: 0,
    iva:10.5,
    badge: '',
    brand: 'Shimaha',
    specs: ['19 Hp', '8,5kW'],
    image: '/fotos/Energia y Potencia/SHP8500E.jpg',
    description: 'Con motor simil Honda, arranque electrico, salida de 220V y bateria incluida.'
  },
  {
    id: 110,
    name: 'Generador electrico',
    category: 'Energia y Potencia',
    subcategory: 'Generadores y Grupos Electrogenos',
    price: 0,
    iva:10.5,
    badge: '',
    brand: 'Shimaha',
    specs: ['16Hp', '6,5kW'],
    image: '/fotos/Energia y Potencia/SHP6500E.jpg',
    description: 'Con motor simil Honda, arranque electrico, salida de 220V y bateria incluida.'
  },
  {
    id: 111,
    name: 'Generador electrico',
    category: 'Energia y Potencia',
    subcategory: 'Generadores y Grupos Electrogenos',
    price: 0,
    iva:10.5,
    badge: '',
    brand: 'Shimaha',
    specs: ['223 cc', '7,5 Hp', '15L', '4T'],
    image: '/fotos/Energia y Potencia/SHGG3500 50E.jpg',
    description: 'Con salida de 220V, arranque electrico y para uso profesional.'
  },
  {
    id: 112,
    name: 'Generador electrico',
    category: 'Energia y Potencia',
    subcategory: 'Generadores y Grupos Electrogenos',
    price: 0,
    iva:10.5,
    badge: '',
    brand: 'Shimaha',
    specs: ['210 cc', '7 Hp', '17L', '4T'],
    image: '/fotos/Energia y Potencia/SHG2800 1 50.jpg',
    description: 'Con salida de 220V, arranque manual, para uso profesional.'
  },

  //DISCONTINUADOS
  {
    id: 113,
    name: 'Mototaladro',
    category: 'Discontinuados',
    price: 0,
    iva:10.5,
    badge: '',
    brand: 'Spartan',
    specs: ['3000 +- 2000rpm', '26cc', '2T'],
    image: '/fotos/Discontinuados/SPGD260.jpg',
    description: 'Con mandril de 13mm, incluye dos mechas y funcion reversa.'
  },
  {
    id: 114,
    name: 'Motosierra',
    category: 'Discontinuados',
    price: 0,
    iva:10.5,
    badge: '',
    brand: 'Spartan',
    specs: ['52cc', '20"', '2T'],
    image: '/fotos/Discontinuados/SPC520.jpg',
    description: 'Para uso liviano con sistema antivibratorio'
  },
  {
    id: 115,
    name: 'Afilador de cadenas',
    category: 'Discontinuados',
    price: 0,
    iva:10.5,
    badge: '',
    brand: 'Spartan',
    specs: [''],
    image: '/fotos/Discontinuados/SPAF-250.jpg',
    description: 'Afilador para cadenas de motosierras con piedra de 3,2mm.'
  },
  {
    id: 116,
    name: 'Pulverizador',
    category: 'Discontinuados',
    price: 0,
    iva:10.5,
    badge: '',
    brand: 'Spartan',
    specs: [''],
    image: '/fotos/Discontinuados/SPP620.jpg',
    description: 'Pulverizador a motor con tanque de 20L, formato mochila y motor de 26cc'
  },
  {
    id: 117,
    name: 'Bomba sumergible',
    category: 'Discontinuados',
    price: 0,
    iva:10.5,
    badge: '',
    brand: 'Gladiator PRO',
    specs: ['2850rpm', '11/2Hp'],
    image: '/fotos/Discontinuados/BPP886 1 25.jpg',
    description: 'Bomba sumergible de pozo profundo con altura maxima de 78m, caudal de 2 a 4 m2 /h y 12 etapas. Incluye tablero.'
  },
  {
    id: 118,
    name: 'Sierra caladora',
    category: 'Discontinuados',
    price: 0,
    iva:10.5,
    badge: '',
    brand: 'Gladiator PRO',
    specs: ['400 W'],
    image: '/fotos/Discontinuados/SK 455 2 220.jpg',
    description: 'Sierra caladora com velocidad en vacio de 500-3.000/min y capacidad de corte de 6mm en acero y 55mm en madera.'
  },
  //EQUIPOS FORESTALES
  {
    id: 119,
    name: 'Astillador rompedor',
    category: 'Equipos forestales',
    subcategory: 'Astilladores y rompedoras',
    badge: '',
    brand: 'HorsePower',
    specs: [''],
    image: '/fotos/Equipos forestales/ATM01.jpg',
    description: 'Apto para madera de 343-460mm de largo y maximo de 205mm.'
  },
  {
    id: 120,
    name: 'Astillador romedor',
    category: 'Equipos forestales',
    subcategory: 'Astilladores y rompedoras',
    badge: '',
    brand: 'HorsePower',
    specs: ['3000 W'],
    image: '/fotos/Equipos forestales/ATE 8TON.jpg',
    description: 'Apto para troncos de 1060mm de largo y 70-400mm, alimentacion de 220V - 50Hz.'
  },
  {
    id: 121,
    name: 'Astillador rompedor a gasolina',
    category: 'Equipos forestales',
    subcategory: 'Astilladores y rompedoras',
    badge: '',
    brand: 'HorsePower',
    specs: ['196cc', '4,8kW', '4T'],
    image: '/fotos/Equipos forestales/ATG 10TON.jpg',
    description: 'Apto para troncos de 1060mm de largo y 70-400mm.'
  },
  {
    id: 122,
    name: 'Astillador rompedor',
    category: 'Equipos forestales',
    subcategory: 'Astilladores y rompedoras',
    badge: '',
    brand: 'HorsePower',
    specs: ['5,2 kVa'],
    image: '/fotos/Equipos forestales/ATE 14TON.jpg',
    description: 'Apto para troncos de hasta 1060mm de largo y 70-400mm, alimentacion de 380V - 50Hz.'
  },
  //PODA Y JARDIN
  {
    id: 123,
    name: 'Motosierra',
    category: 'Jardin y Poda',
    subcategory: 'Motosierras',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['25cc', '12"', '2T'],
    image: '/fotos/Poda y Jardin/CS2500.jpg',
    description: 'Con sistema antivibratprio, cadena/paso 3/8 Lp y arranque facil. Para uso intensivo.'
  },
  {
    id: 124,
    name: 'Motosierra',
    category: 'Jardin y Poda',
    subcategory: 'Motosierras',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['38,2cc', '16"', '2T'],
    image: '/fotos/Poda y Jardin/CS3800.jpg',
    description: 'Con sistema antivibratorio, cadena/paso 3/8 Lp y arranque facil. Para uso intensivo.'
  },
  {
    id: 125,
    name: 'Motosierra',
    category: 'Jardin y Poda',
    subcategory: 'Motosierras',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['45cc', '18"', '2T'],
    image: '/fotos/Poda y Jardin/CS4500.jpg',
    description: 'Con sistema antivibratorio, cadena/paso 325.058 y arranque facil. Para uso intensivo.'
  },
  {
    id: 126,
    name: 'Motosierra',
    category: 'Jardin y Poda',
    subcategory: 'Motosierras',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['52cc', '20"', '2T'],
    image: '/fotos/Poda y Jardin/CS5200.jpg',
    description: 'Con sistema antivibratorio, cadena/paso 325 y arranque facil. Para uso intensivo.'
  },
  {
    id: 127,
    name: 'Motosierra',
    category: 'Jardin y Poda',
    subcategory: 'Motosierras',
    badge: '',
    brand: 'Wolfox',
    specs: ['45cc', '18"', '2T'],
    image: '/fotos/Poda y Jardin/WF0860.jpg',
    description: 'Con relacion de mezcla 25:1, cadena de 325.058. Para uso intensivo.'
  },
  {
    id: 128,
    name: 'Motosierra',
    category: 'Jardin y Poda',
    subcategory: 'Motosierras',
    badge: '',
    brand: 'Green Cut',
    specs: ['52cc', '20"', '2T'],
    image: '/fotos/Poda y Jardin/GCCS520-1.jpg',
    description: 'Con sistema antivibratorio, bombin y kit de herramientas. Para uso liviano.'
  },
  {
    id: 129,
    name: 'Combo Rompedor',
    category: 'Jardin y Poda',
    subcategory: 'Motosierras',
    badge: '',
    brand: 'SHIMAHA',
    specs: [''],
    image: '/fotos/Poda y Jardin/ROM-REM.jpg',
    description: 'Combo rompedor + remachador de cadena.'
  },
  {
    id: 130,
    name: 'Afilador de cadena',
    category: 'Jardin y Poda',
    subcategory: 'Motosierras',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['3.000rpm', '230W'],
    image: '/fotos/Poda y Jardin/ES009.jpg',
    description: 'Velocidad de 3.000rpm, motor directo sin carbones y diseño para uso intensivo.'
  },
  {
    id: 131,
    name: 'Afilador de cadena',
    category: 'Jardin y Poda',
    subcategory: 'Motosierras',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['4.800rpm', '85W'],
    image: '/fotos/Poda y Jardin/ES2002B.jpg',
    description: 'Con motor directo con carbones y diseño indicado para uso hobbista.'
  },
  {
    id: 132,
    name: 'Tractor',
    category: 'Jardin y Poda',
    subcategory: 'Tractores y accesorios',
    badge: '',
    brand: 'Cub Cadet',
    specs: ['19Hp', '547cc'],
    image: '/fotos/Poda y Jardin/13A6A9TS010.jpg',
    description: 'Tractor con 42"cm de corte, velocidad crucero, tren delantero de fundicion.'
  },
  {
    id: 133,
    name: 'Tractor',
    category: 'Jardin y Poda',
    subcategory: 'Tractores y accesorios',
    badge: '',
    brand: 'Cub Cadet',
    specs: ['22Hp', '725cc'],
    image: '/fotos/Poda y Jardin/13APA9TTA10.jpg',
    description: 'Tractor con 46"cm de corte, velocidad crucero, tren delantero de fundicion.'
  },
  {
    id: 134,
    name: 'Tractor',
    category: 'Jardin y Poda',
    subcategory: 'Tractores y accesorios',
    badge: '',
    brand: 'Cub Cadet',
    specs: ['23Hp', '679cc'],
    image: '/fotos/Poda y Jardin/13BJA1TL342.jpg',
    description: 'Tractor con 50"cm de corte, velocidad crucero, tren delantero de fundicion.'
  },
  {
    id: 135,
    name: 'Tractor giro cero',
    category: 'Jardin y Poda',
    subcategory: 'Tractores y accesorios',
    badge: '',
    brand: 'Cub cadet',
    specs: ['24Hp', '726cc'],
    image: '/fotos/Poda y Jardin/17BIEAC5010.jpg',
    description: 'Tractor giro cero con corte de 60", motor Kawasaki bicilindrico y transmision hidrostatica.'
  },
  {
    id: 136,
    name: 'Tractor',
    category: 'Jardin y Poda',
    subcategory: 'Tractores y accesorios',
    badge: '',
    brand: 'Shimaha',
    specs: ['452cc', '7,5L'],
    image: '/fotos/Poda y Jardin/SHM38HS-D452.jpg',
    description: 'Tractor sin bolsa, con corte de 36", transmision hidrostatica, 7 posiciones de altura, salida lateral y triturador.'
  },
  {
    id: 137,
    name: 'Tractor',
    category: 'Jardin y Poda',
    subcategory: 'Tractores y accesorios',
    badge: '',
    brand: 'Shimaha',
    specs: ['15Hp', '452cc', '7,5L'],
    image: '/fotos/Poda y Jardin/STRA 836-15.jpg',
    description: 'Tractor con bolsa, con capacidad de recoleccion 245L, corte de 36", transmision automatica, arranque electrico y 7 niveles de altura de corte.'
  },
  {
    id: 138,
    name: 'Motor',
    category: 'Jardin y Poda',
    subcategory: 'Tractores y accesorios',
    badge: '',
    brand: 'Loncin',
    specs: ['452cc', '16Hp', '4T'],
    image: '/fotos/Poda y Jardin/LC1P92F1.jpg',
    description: 'Para tractor con arranque electrico, eje de 1" y bomba de aceite.'
  },
  {
    id: 139,
    name: 'Recolector',
    category: 'Jardin y Poda',
    subcategory: 'tractores y accesorios',
    badge: '',
    brand: 'TROY-BILT',
    specs: [''],
    image: '/fotos/Poda y Jardin/19A300110EM.jpg',
    description: 'Recolector para rider TROY-BILT / CRAFTSMAN de 30".'
  },
  {
    id: 140,
    name: 'Recolector',
    category: 'Jardin y Poda',
    subcategory: 'tractores y accesorios',
    badge: '',
    brand: 'John Deere',
    specs: [''],
    image: '/fotos/Poda y Jardin/BM21888.jpg',
    description: 'Recolector para mini tractor John Deere series 100 de 42".'
  },
  {
    id: 141,
    name: 'Desmalezadora',
    category: 'Jardin y Poda',
    subcategory: 'Desmalezadoras, Bordeadoras y Mas',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['52cc', '2T'],
    image: '/fotos/Poda y Jardin/TB520.jpg',
    description: 'Desmalezadora con motor tipo Mitsubishi, sistema antivibratorio y cardan de 28mm. Para uso intensivo.'
  },
  {
    id: 142,
    name: 'Desmalezadora',
    category: 'Jardin y Poda',
    subcategory: 'Desmalezadoras, Bordeadoras y Mas',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['52cc', '2T'],
    image: '/fotos/Poda y Jardin/TT-BC520.jpg',
    description: 'Desmalezadora con motor tipo Mitsubishi, sistema antivibratorio y cardan de 26mm. Para uso intensivo.'
  },
  {
    id: 143,
    name: 'Desmalezadora',
    category: 'Jardin y Poda',
    subcategory: 'Desmalezadoras, Bordeadoras y Mas',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['43cc', '2T'],
    image: '/fotos/Poda y Jardin/TU 43-SH.jpg',
    description: 'Desmalezadora con motor Mitsubishi, sistema antivibratorio y cardan de 28mm. Para uso intensivo.'
  },
  {
    id: 144,
    name: 'Desmalezadora',
    category: 'Jardin y Poda',
    subcategory: 'Desmalezadoras, Bordeadoras y Mas',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['43cc', '2T'],
    image: '/fotos/Poda y Jardin/G45.jpg',
    description: 'Desmalezadora con sistema antivibratorio, cardan de 28mm y arnes profesional. Para uso intensivo.'
  },
  {
    id: 145,
    name: 'Desmalezadora',
    category: 'Jardin y Poda',
    subcategory: 'Desmalezadoras, Bordeadoras y Mas',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['35,8cc', '4T'],
    image: '/fotos/Poda y Jardin/SHD 836-4.jpg',
    description: 'Desmalezadora con motor tipo Honda, sistema antivibratoriom arranque facil y arnes anatomico. Para uso intensivo.'
  },
  {
    id: 146,
    name: 'Bordeadora',
    category: 'Jardin y Poda',
    subcategory: 'Desmalezadoras, Bordeadoras y Mas',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['26cc', '2T'],
    image: '/fotos/Poda y Jardin/CG260E.jpg',
    description: 'Bordeadora con motor tipo Mitsubishi, con sistema antivibratorio y cardan de eje curvo. Para uso intensivo.'
  },
  {
    id: 147,
    name: 'Equipo multifuncion',
    category: 'Jardin y Poda',
    subcategory: 'Desmalezadoras, Bordeadoras y Mas',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['52cc', '2T'],
    image: '/fotos/Poda y Jardin/SHD8524-1.jpg',
    description: 'Equipo multifuncion con desmalezadora, cortacerco y podador de altura de 10". Para uso intensivo.'
  },
  {
    id: 148,
    name: 'Podador',
    category: 'Jardin y Poda',
    subcategory: 'Desmalezadoras, Bordeadoras y Mas',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['26cc', '2T'],
    image: '/fotos/Poda y Jardin/PS260-4M.jpg',
    description: 'Podador de altura con motor tipo Mitsubishi, alcance de 4 metros y sistmea antivibratorio. Para uso intensivo.'
  },
  {
    id: 149,
    name: 'Bordeadora',
    category: 'Jardin y Poda',
    subcategory: 'Desmalezadoras, Bordeadoras y Mas',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['550W'],
    image: '/fotos/Poda y Jardin/BP620.jpg',
    description: 'Bordeadora electrica con conrte de 300mm, carretel automatico y montada con rulemanes. Para uso intensivo.'
  },
  {
    id: 150,
    name: 'Bordeadora',
    category: 'Jardin y Poda',
    subcategory: 'Desmalezadoras, Bordeadoras y Mas',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['1000W'],
    image: '/fotos/Poda y Jardin/BP1000.jpg',
    description: 'Bordeadora electrica con corte de 300mm, carretel automatico y montada con rulemanes Para uso intensivo.'
  },
  {
    id: 151,
    name: 'Desmalezadora',
    category: 'Jardin y Poda',
    subcategory: 'Desmalezadoras, Bordeadoras y Mas',
    badge: '',
    brand: 'Green Cut',
    specs: ['52cc', '2T'],
    image: '/fotos/Poda y Jardin/BCB52.jpg',
    description: 'Desmalezadora con motor tipo Mitsubishi, sistema antivibratorio y arranque facil. Para uso intesivo.'
  },
  {
    id: 152,
    name: 'Desmalezadora',
    category: 'Jardin y Poda',
    subcategory: 'Desmalezadoras, Bordeadoras y Mas',
    badge: '',
    brand: 'RHINO',
    specs: ['52cc', '2T'],
    image: '/fotos/Poda y Jardin/RH52.jpg',
    description: 'Desmalezadora con motor tipo Mitsubishi, sistema antivibratorio y cardan de 26mm. Para uso intensivo.'
  },
  {
    id: 153,
    name: 'Desmalezadora',
    category: 'Jardin y Poda',
    subcategory: 'Desmalezadoras, Bordeadoras y Mas',
    badge: '',
    brand: 'SPARTAN',
    specs: ['52cc', '2T'],
    image: '/fotos/Poda y Jardin/SPBC520.jpg',
    description: 'Desmalezadora a explosion, sistema antivibratorio, cardan de 26mm. Para uso liviano.'
  },
  {
    id: 154,
    name: 'Cortacerco',
    category: 'Jardin y Poda',
    subcategory: 'Desmalezadoras, Bordeadoras y Mas',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['22,5cc', '600mm', '2T'],
    image: '/fotos/Poda y Jardin/SH-Ht230H.jpg',
    description: 'Cortacerco con cuchilla de doble filo. Para uso liviano.'
  },
  {
    id: 155,
    name: 'Sopla aspirador triturador',
    category: 'Jardin y Poda',
    subcategory: 'Desmalezadoras, Bordeadoras y Mas',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['25,4cc'],
    image: '/fotos/Poda y Jardin/SH-BV3405.jpg',
    description: 'Sopla aspirador triturador con velocidad de 62,7 m/s, potencia de 0,75kW. Para uso intensivo.'
  },
  {
    id: 156,
    name: 'Sopla aspirador triturador',
    category: 'Jardin y Poda',
    subcategory: 'Desmalezadoras, Bordeadoras y Mas',
    badge: '',
    brand: 'Green Cut',
    specs: ['26cc', '1 Hp'],
    image: '/fotos/Poda y Jardin/GCS045.jpg',
    description: 'Con velocidad de aire de 265 km/h y unidades de barrido de 45. Para uso Hogareño.'
  },
  {
    id: 157,
    name: 'Cortadora de cesped',
    category: 'Jardin y Poda',
    subcategory: 'Cortadoras, Motor y Casco',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['3/4 Hp'],
    image: '/fotos/Poda y Jardin/SH1000.jpg',
    description: 'Con corte de 350mm, bolsa recolectora de 30L, 3 posiciones de corte y chasis de acero.'
  },
  {
    id: 158,
    name: 'Cortadora de cesped',
    category: 'Jardin y Poda',
    subcategory: 'Cortadoras, Motor y Casco',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['1 Hp'],
    image: '/fotos/Poda y Jardin/SH1200.jpg',
    description: 'Con corte de 450mm, bolsa recolectora de 55L, 5 posiciones de corte independientes y chasis de acero.'
  },
  {
    id: 159,
    name: 'Cortadora de cesped',
    category: 'Jardin y Poda',
    subcategory: 'Cortadoras, Motor y Casco',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['1,5 Hp'],
    image: '/fotos/Poda y Jardin/SH1600.jpg',
    description: 'Con corte de 450mm, bolsa recolectora de 55L, 5 posiciones de corte independientes y chasis de acero.'
  },
  {
    id: 160,
    name: 'Cortadora de cesped',
    category: 'Jardin y Poda',
    subcategory: 'Cortadoras, Motor y Casco',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['6,5 Hp'],
    image: '/fotos/Poda y Jardin/GSA22-SH F650.jpg',
    description: 'Con ancho de corte de 22", 5 posiciones de corte, salida lateral y chasis de acero.'
  },
  {
    id: 161,
    name: 'Cortadora de cesped',
    category: 'Jardin y Poda',
    subcategory: 'Cortadoras, Motor y Casco',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['146cc'],
    image: '/fotos/Poda y Jardin/SHS 531.jpg',
    description: 'Con ancho de corte de 20", regulacion individual de altura, ruedas con rulemanes y funcion de triturado y descarga lateral.'
  },
  {
    id: 162,
    name: 'Cortadora de cesped',
    category: 'Jardin y Poda',
    subcategory: 'Cortadoras, Motor y Casco',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['196cc'],
    image: '/fotos/Poda y Jardin/SHSB31HY.jpg',
    description: '3 en 1 con ancho de corte de 21", ajuste de altura de 25 a 75mm, funcion de triturado y bolsa recolectora de 70L.'
  },
  {
    id: 163,
    name: 'Cortadora de cesped',
    category: 'Jardin y Poda',
    subcategory: 'Cortadoras, Motor y Casco',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['7hp'],
    image: '/fotos/Poda y Jardin/SHGLM22B.jpg',
    description: '4 en 1 autopropulsada, con 7 posiciones de corte, traccion trasera y bolsa recolectora de 60L.'
  },
  {
    id: 164,
    name: 'Cortadora de cesped',
    category: 'Jardin y Poda',
    subcategory: 'Cortadoras, Motor y Casco',
    badge: '',
    brand: 'Cub Cadet',
    specs: ['163cc'],
    image: '/fotos/Poda y Jardin/11AB9C2010.jpg',
    description: '3 en 1 con ancho de corte de 21", 6 posiciones de altura y ruedas traseras de 11".'
  },
  {
    id: 165,
    name: 'Cortadora de cesped',
    category: 'Jardin y Poda',
    subcategory: 'Cortadoras, Motor y Casco',
    badge: '',
    brand: 'Cub Cadet',
    specs: ['163cc'],
    image: '/fotos/Poda y Jardin/12AVB2V2010.jpg',
    description: '4 en 1, con ancho de corte de 21", traccion delantera y 6 alturas de corte.'
  },
  {
    id: 166,
    name: 'Casco protector',
    category: 'Jardin y Poda',
    subcategory: 'Cortadoras, Motor y Casco',
    badge: '',
    brand: 'SHIMAHA',
    specs: [''],
    image: '/fotos/Poda y Jardin/P55T.jpg',
    description: 'Con proteccion integral para craneo, rostro y oidos, ideal para trabajos forestales y de corte.'
  },
  {
    id: 167,
    name: 'Motor',
    category: 'Jardin y Poda',
    subcategory: 'Motores',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['3600rpm', '7hp', '3,6L'],
    image: '/fotos/Poda y Jardin/170F.jpg',
    description: 'Motor horizontal con arranque manual, eje de 20mm y sensor de aceite.'
  },
  {
    id: 168,
    name: 'Motor',
    category: 'Jardin y Poda',
    subcategory: 'Motores',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['3600rpm', '13hp', '6,5L'],
    image: '/fotos/Poda y Jardin/188F.jpg',
    description: 'Motor horizontal con arranque manual, eje de 25 mm y sensor de aceite.'
  },
  {
    id: 169,
    name: 'Motor',
    category: 'Jardin y Poda',
    subcategory: 'Motores',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['3600rpm', '13hp', '6,5L'],
    image: '/fotos/Poda y Jardin/188F-E.jpg',
    description: 'Motor horizontal con arranque electrico, eje de 25 mm y sensor de aceite.'
  },
  {
    id: 170,
    name: 'Motor',
    category: 'Jardin y Poda',
    subcategory: 'Motores',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['3600rpm', '15hp', '6,5L'],
    image: '/fotos/Poda y Jardin/PT420.jpg',
    description: 'Motor horizontal con arranque manual, eje de 25 mm y sensor de aceite.'
  },
  {
    id: 171,
    name: 'Motor',
    category: 'Jardin y Poda',
    subcategory: 'Motores',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['3600rpm', '15hp', '6,5L'],
    image: '/fotos/Poda y Jardin/W190F.jpg',
    description: 'Motor horizontal con arranque electrico, eje de 25 mm y sensor de aceite.'
  },
  {
    id: 172,
    name: 'Motor',
    category: 'Jardin y Poda',
    subcategory: 'Motores',
    badge: '',
    brand: 'Tillotson',
    specs: ['98cc', '3,5hp', '1L'],
    image: '/fotos/Poda y Jardin/MOTOR VERTICAL 2.jpg',
    description: 'Motor vertical para cortadoras con eje de 22 x 55mm y sistema OHV.'
  },
  {
    id: 173,
    name: 'Motor',
    category: 'Jardin y Poda',
    subcategory: 'Motores',
    badge: '',
    brand: 'Tillotson',
    specs: ['140cc', '5hp', '1,2L'],
    image: '/fotos/Poda y Jardin/MOTOR VERTICAL.jpg',
    description: 'Motor vertical para cortadora con eje de 22 x 55 mm y sistema OHV.'
  },
  {
    id: 174,
    name: 'Motor',
    category: 'Jardin y Poda',
    subcategory: 'Motores',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['224cc', '7hp', '1,2L'],
    image: '/fotos/Poda y Jardin/DV224.jpg',
    description: 'Motor para cortadora con eje de 22mm, largo de eje de 85mm y capacidad de aceite de 0,50 L.'
  },
  {
    id: 175,
    name: 'Motor',
    category: 'Jardin y Poda',
    subcategory: 'Motores',
    badge: '',
    brand: 'BRIGGS & STRATTON',
    specs: ['5hp', '190cc'],
    image: '/fotos/Poda y Jardin/BS-5.0HP.jpg',
    description: 'Motor para cortador con eje de 22,5mm.'
  },
  {
    id: 176,
    name: 'Motobomba',
    category: 'Jardin y Poda',
    subcategory: 'Motobombas y Bombas',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['7hp', '4T', '2"'],
    image: '/fotos/Poda y Jardin/WP50.jpg',
    description: 'Motobomba con altura maxima de 28m, succion maxima de 7m y caudal maximo de 30 L/min.'
  },
  {
    id: 178,
    name: 'Motobomba',
    category: 'Jardin y Poda',
    subcategory: 'Motobombas y Bombas',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['7hp', '4T', '3"'],
    image: '/fotos/Poda y Jardin/00-WP80.jpg',
    description: 'Motobomba con altura maxima de 30m, succion maxima de 7m y caudal maximo de 30 L/min.'
  },
  {
    id: 179,
    name: 'Motobomba',
    category: 'Jardin y Poda',
    subcategory: 'Motobombas y Bombas',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['15hp', '4"'],
    image: '/fotos/Poda y Jardin/WB40CX.jpg',
    description: 'Motobomba con elevacion maxima de 50m, succion de 16m y caudal maximo de 78 m3/h.'
  },
  {
    id: 180,
    name: 'Bomba periferica',
    category: 'Jardin y Poda',
    subcategory: 'Motobombas y Bombas',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['2840rpm', '1/2hp'],
    image: '/fotos/Poda y Jardin/SHP 12 25.jpg',
    description: 'Con altura manometrica maxima de 9m, succion maxima de 8m y caudal maximo de 12 L/min.'
  },
  {
    id: 181,
    name: 'Sacapanes',
    category: 'Jardin y Poda',
    subcategory: 'Equipos Varios',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['9hp', '4T'],
    image: '/fotos/Poda y Jardin/SGHSC9.jpg',
    description: 'Sacapanes con motor Honda GX270, ancho de corte de 45cm, profundidad de 5cm. Para uso intensivo.'
  },
  {
    id: 182,
    name: 'Sacapanes',
    category: 'Jardin y Poda',
    subcategory: 'Equipos Varios',
    badge: '',
    brand: 'Classen',
    specs: ['6,5hp', '4T'],
    image: '/fotos/Poda y Jardin/SC18 5.5.jpg',
    description: 'Con motor Honda GC160, ancho de corte de 45cm, profundidad de 3cm. Para uso intensivo.'
  },
  {
    id: 183,
    name: 'Chipeadora',
    category: 'Jardin y Poda',
    subcategory: 'Equipos Varios',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['196cc', '6,5hp', '4T'],
    image: '/fotos/Poda y Jardin/AYS850.jpg',
    description: 'Chipeadora con entrada de 60mm, transmision de 2 correas, arranque manual. Para uso intensivo.'
  },
  {
    id: 184,
    name: 'Zanjadora',
    category: 'Jardin y Poda',
    subcategory: 'Equipos Varios',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['7hp'],
    image: '/fotos/Poda y Jardin/SHGTR7.jpg',
    description: 'Zanjadora con motor Honda GX200, ancho de zanja de 10cm, profundidad de 30 cm y largo de corte de 45cm.'
  },
  {
    id: 185,
    name: 'Mototaladro',
    category: 'Jardin y Poda',
    subcategory: 'Equipos Varios',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['3000+-200rpm', '26cc', '2T'],
    image: '/fotos/Poda y Jardin/SHMT-826.jpg',
    description: 'Mototaladro con broca de 13x230 /28x350mm, mezcla de 25:1 y funcion reversa. Incluye 2 mechas.'
  },
  {
    id: 186,
    name: 'Hoyadora',
    category: 'Jardin y Poda',
    subcategory: 'Equipos Varios',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['63cc', '2T'],
    image: '/fotos/Poda y Jardin/DZ-63.jpg',
    description: 'Hoyadora con motor Mitsubishi, sistema antivibratorio, aranque facil y mecha de 300 x 800mm. Para uso intensivo.'
  },
  {
    id: 187,
    name: 'Hoyadora',
    category: 'Jardin y Poda',
    subcategory: 'Equipos Varios',
    badge: '',
    brand: 'SPARTAN',
    specs: ['52cc', '2T'],
    image: '/fotos/Poda y Jardin/SPEA520.jpg',
    description: 'Hoyadora con mecha de 200 x 800 mm. Para uso liviano.'
  },
  {
    id: 188,
    name: 'Mecha de Hoyadora',
    category: 'Jardin y Poda',
    subcategory: 'Equipos Varios',
    badge: '',
    brand: 'SHIMAHA',
    specs: [''],
    image: '/fotos/Poda y Jardin/MECHA HOYADORA.jpg',
    description: 'Mecha de Hoyadora de 100mm.'
  },
  {
    id: 189,
    name: 'Zorra portapallets reforzada',
    category: 'Jardin y Poda',
    subcategory: 'Equipos Varios',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['3000 Kg'],
    image: '/fotos/Poda y Jardin/BF30.jpg',
    description: 'Diseñada para soportar equipos de hasta 3000Kg.'
  },
  {
    id: 190,
    name: 'Hidrolavadora',
    category: 'Jardin y Poda',
    subcategory: 'Hidrolavadoras y Motocultivadoras',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['170 bar', '196cc', '6,5hp', '4T'],
    image: '/fotos/Poda y Jardin/GWP170.jpg',
    description: 'Hidrolavadora a explosion con caudal de 500L/h, bomba axial de 4 pistones. Para uso intensivo.'
  },
  {
    id: 191,
    name: 'Hidrolavadora',
    category: 'Jardin y Poda',
    subcategory: 'Hidrolavadoras y Motocultivadoras',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['300bar', '389cc', '13hp', '4T'],
    image: '/fotos/Poda y Jardin/GPW300.jpg',
    description: 'Hidrolavadora a explosion con caudal de 780 L/h, bomba lineal con cigueñal. Para uso intensivo.'
  },
  {
    id: 192,
    name: 'Hidrolavadora electrica',
    category: 'Jardin y Poda',
    subcategory: 'Hidrolavadoras y Motocultivadoras',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['110 bar', '1400W'],
    image: '/fotos/Poda y Jardin/SH 4110.jpg',
    description: 'Hidrolavadora electrica con caudal maximo de 5,1 L/min, proteccion IPX5 y sistema Auto-Stop.'
  },
  {
    id: 193,
    name: 'Hidorlavadora electrica',
    category: 'Jardin y Poda',
    subcategory: 'Hidrolavadoras y Motocultivadoras',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['130bar', '1600W'],
    image: '/fotos/Poda y Jardin/SH 6130M.jpg',
    description: 'Hidorlavadora electrica con caudal maximo de 5,2 L/min, proteccion IPX5 y sistema Auto-Stop.'
  },
  {
    id: 194,
    name: 'Hidrolavadora electrica',
    category: 'Jardin y Poda',
    subcategory: 'Hidrolavadoras y Motocultivadoras',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['160bar', '2200W'],
    image: '/fotos/Poda y Jardin/SH 7160RM.jpg',
    description: 'Hidrolavadora electrica con caudal maximo de 5,6 L/min, proteccion IPX5 y sistema Auto-Stop.'
  },
  {
    id: 195,
    name: 'Hidrolavadora electrica',
    category: 'Jardin y Poda',
    subcategory: 'Hidrolavadoras y Motocultivadoras',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['140bar', '2000W'],
    image: '/fotos/Poda y Jardin/SH 9140RM.jpg',
    description: 'Hidrolavadora electrica con motor a induccion sin carbones, caudal maximo de 6,7 L/min, proteccion IPX5 y sistema Auto-Stop.'
  },
  {
    id: 196,
    name: 'Motocultivador',
    category: 'Jardin y Poda',
    subcategory: 'Hidrolavadoras y Motocultivadoras',
    badge: 'PROXIMAMENTE',
    brand: 'SHIMAHA',
    specs: ['6,5hp', '4T'],
    image: '/fotos/Poda y Jardin/00-GT212C.jpg',
    description: 'Con motor Honda, selector de giro de cuchillas, traccion cardanica y ruedas mecizas agricolas.'
  },
  {
    id: 197,
    name: 'Motocultivador',
    category: 'Jardin y Poda',
    subcategory: 'Hidrolavadoras y Motocultivadoras',
    badge: '',
    brand: 'SHIMAHA',
    specs: ['7hp', '4T'],
    image: '/fotos/Poda y Jardin/HHGT-001.jpg',
    description: 'Con motor Honda, arranque manual, labrado de hasta 50cm, y traccion cardanica.'
  },
  {
    id: 198,
    name: 'Pulverizador',
    category: 'Jardin y Poda',
    subcategory:  'Pulverizadores, Fumigadores y Mas',
    badge: '',
    brand: 'SHIMAHA',
    specs: [''],
    image: '/fotos/Poda y Jardin/SX-5073-6.jpg',
    description: 'Pulverizador manual con capacidad de 2 litros, compacto y practico para aplicaciones manuales.'
  },
  {
    id: 199,
    name: 'Pulverizador',
    category: 'Jardin y Poda',
    subcategory:  'Pulverizadores, Fumigadores y Mas',
    badge: '',
    brand: 'SHIMAHA',
    specs: [''],
    image: '/fotos/Poda y Jardin/SX-CS5B.jpg',
    description: 'Pulverizador manual con capacidad de 5 litros, ideal para aplicaciones de pulverizacion general.'
  },
  {
    id: 200,
    name: 'Pulverizador',
    category: 'Jardin y Poda',
    subcategory:  'Pulverizadores, Fumigadores y Mas',
    badge: '',
    brand: 'Green Pro',
    specs: [''],
    image: '/fotos/Poda y Jardin/GPSP8L.jpg',
    description: 'Pulverizador manual con capacidad de 8 litros, diseñado para aplicaciones de mayor autonomia.'
  },
  {
    id: 201,
    name: 'Pulverizador',
    category: 'Jardin y Poda',
    subcategory:  'Pulverizadores, Fumigadores y Mas',
    badge: '',
    brand: 'SHIMAHA',
    specs: [''],
    image: '/fotos/Poda y Jardin/SX-LK15A-1.jpg',
    description: 'Pulverizador manual tipo mochila con capacidad de 15 litros y accesorios incluidos.'
  },
  {
    id: 202,
    name: 'Pulverizador',
    category: 'Jardin y Poda',
    subcategory:  'Pulverizadores, Fumigadores y Mas',
    badge: '',
    brand: 'SHIMAHA',
    specs: [''],
    image: '/fotos/Poda y Jardin/SHPG825.jpg',
    description: 'Pulverizador con tanque de 25 litros, de 1" y para uso intensivo, incluye kit de herramientas.'
  },
  {
    id: 203,
    name: 'Fumigador',
    category: 'Jardin y Poda',
    subcategory:  'Pulverizadores, Fumigadores y Mas',
    badge: '',
    brand: 'SPARTAN',
    specs: [''],
    image: '/fotos/Poda y Jardin/SPF4220.jpg',
    description: 'Fumigador con tanque de 20 litros, velocidad de 7500 rpm y para uso semiprofesional.'
  },
  {
    id: 204,
    name: 'Escalera de aluminio multiusos',
    category: 'Jardin y Poda',
    subcategory:  'Pulverizadores, Fumigadores y Mas',
    badge: '',
    brand: 'SHIMAHA',
    specs: [''],
    image: '/fotos/Poda y Jardin/SHR-14204.jpg',
    description: 'Escalera de aluminio multiusos, diseño pleglable con cerraduras de seguridad, barras estabilizadoras y bisagras reforzadas en aluminio de 1,2 mm.'
  },
  {
    id: 205,
    name: 'Barrehojas',
    category: 'Jardin y Poda',
    subcategory:  'Pulverizadores, Fumigadores y Mas',
    badge: '',
    brand: 'SHIMAHA',
    specs: [''],
    image: '/fotos/Poda y Jardin/SX-H03.jpg',
    description: 'Barrehojas super reforzado con 60cm de ancho.'
  },




 

















];